-- PUB."fam-comerc" definição

-- Drop table

-- DROP TABLE PUB."fam-comerc";

CREATE TABLE PUB."fam-comerc" (
	"fm-cod-com" varchar(16) NOT NULL,
	descricao varchar(60) NOT NULL,
	"baixa-estoq" integer DEFAULT 1 NOT NULL,
	"ind-imp-desc" integer DEFAULT 1 NOT NULL,
	un varchar(4) NOT NULL,
	"tp-aloc-lote" integer DEFAULT 1,
	"fator-conver" numeric(20,5) DEFAULT 1,
	"char-1" varchar(200),
	"char-2" varchar(200),
	"dec-1" numeric(23,8) DEFAULT 0,
	"dec-2" numeric(23,8) DEFAULT 0,
	"int-1" integer DEFAULT 0,
	"int-2" integer DEFAULT 0,
	"log-1" bit DEFAULT 0,
	"log-2" bit DEFAULT 0,
	"data-1" date DEFAULT NULL,
	"data-2" date DEFAULT NULL,
	"check-sum" varchar(40),
	"log-aloc-neg" bit DEFAULT 0,
	CONSTRAINT codigo PRIMARY KEY ("fm-cod-com")
);


-- PUB.familia definição

-- Drop table

-- DROP TABLE PUB.familia;

CREATE TABLE PUB.familia (
	"fm-codigo" varchar(16) NOT NULL,
	descricao varchar(60) NOT NULL,
	"loc-unica" bit DEFAULT 1 NOT NULL,
	"tipo-con-est" integer DEFAULT 1 NOT NULL,
	"deposito-pad" varchar(6) NOT NULL,
	"ciclo-contag" integer DEFAULT 0 NOT NULL,
	"curva-abc" bit DEFAULT 1 NOT NULL,
	"moeda-padrao" integer DEFAULT 0 NOT NULL,
	"cod-comprado" varchar(24) NOT NULL,
	demanda integer DEFAULT 1 NOT NULL,
	"emissao-ord" integer DEFAULT 1 NOT NULL,
	politica integer DEFAULT 1 NOT NULL,
	"periodo-fixo" integer DEFAULT 1 NOT NULL,
	"lote-economi" numeric(19,4) DEFAULT 1 NOT NULL,
	"tipo-est-seg" integer DEFAULT 1,
	"tempo-segur" integer DEFAULT 7 NOT NULL,
	"quant-segur" numeric(19,4) DEFAULT 0 NOT NULL,
	"res-int-comp" integer DEFAULT 0 NOT NULL,
	"res-for-comp" integer DEFAULT 0 NOT NULL,
	"res-cq-comp" integer DEFAULT 0 NOT NULL,
	"ressup-fabri" integer DEFAULT 0 NOT NULL,
	"res-cq-fabri" integer DEFAULT 0 NOT NULL,
	"lote-multipl" numeric(19,4) DEFAULT 1 NOT NULL,
	"tipo-lote-ec" integer DEFAULT 1 NOT NULL,
	"classe-repro" integer DEFAULT 1 NOT NULL,
	"contr-qualid" bit DEFAULT 0 NOT NULL,
	"codigo-orig" integer DEFAULT 1 NOT NULL,
	"cd-trib-icm" integer DEFAULT 1 NOT NULL,
	"cd-trib-ipi" integer DEFAULT 1 NOT NULL,
	"cd-trib-iss" integer DEFAULT 1 NOT NULL,
	"fator-conver" numeric(20,5) DEFAULT 1 NOT NULL,
	"fator-refugo" numeric(17,2) DEFAULT 0 NOT NULL,
	"baixa-estoq" bit DEFAULT 1 NOT NULL,
	"class-fiscal" varchar(20) NOT NULL,
	"cd-planejado" varchar(24) NOT NULL,
	"tipo-requis" integer DEFAULT 1 NOT NULL,
	"invent-cla-a" bit DEFAULT 1,
	"invent-cla-b" bit DEFAULT 1,
	"invent-cla-c" bit DEFAULT 1,
	"ind-cons-prv" numeric(17,2) DEFAULT 1 NOT NULL,
	"fator-ponder" varchar(48) DEFAULT '1' NOT NULL,
	un varchar(4) NOT NULL,
	"nr-linha" integer DEFAULT 0 NOT NULL,
	fraciona bit DEFAULT 1 NOT NULL,
	"reporte-mob" integer DEFAULT 1 NOT NULL,
	"tipo-contr" integer DEFAULT 2 NOT NULL,
	"ind-imp-desc" integer DEFAULT 1 NOT NULL,
	"lote-minimo" numeric(19,4) DEFAULT 1 NOT NULL,
	"ind-inf-qtf" bit DEFAULT 0 NOT NULL,
	"vl-min-inv" numeric(19,4) DEFAULT 0,
	"vl-max-inv" numeric(19,4) DEFAULT 0,
	"cap-est-fabr" numeric(19,4) DEFAULT 0 NOT NULL,
	"quant-perda" numeric(19,4) DEFAULT 0 NOT NULL,
	"var-quantid" integer DEFAULT 0 NOT NULL,
	"var-preco" integer DEFAULT 0 NOT NULL,
	"cod-servico" integer DEFAULT 0 NOT NULL,
	"perm-saldo-neg" integer DEFAULT 1 NOT NULL,
	criticidade integer DEFAULT 1 NOT NULL,
	"div-ordem" integer DEFAULT 1 NOT NULL,
	"var-qtd-perm" numeric(17,2) DEFAULT 0 NOT NULL,
	"var-pre-perm" numeric(17,2) DEFAULT 0 NOT NULL,
	sazonalidade varchar(144) DEFAULT '0' NOT NULL,
	"rep-prod" integer DEFAULT 1 NOT NULL,
	"cd-formula" integer DEFAULT 0,
	"cd-origem" integer DEFAULT 1,
	"tp-cons-prev" numeric(15,0) DEFAULT 0,
	"tp-adm-lote" integer DEFAULT 1,
	"per-rest-icms" numeric(17,2) DEFAULT 0 NOT NULL,
	"niv-rest-icms" varchar(2),
	prioridade integer DEFAULT 0 NOT NULL,
	"tipo-sched" integer DEFAULT 1 NOT NULL,
	nivel integer DEFAULT 0 NOT NULL,
	"tipo-insp" integer DEFAULT 1 NOT NULL,
	"perc-nqa" numeric(17,2) DEFAULT 0,
	"atu-conf" bit DEFAULT 0,
	"horiz-fixo" integer DEFAULT 0 NOT NULL,
	"var-req-menor" numeric(17,2) DEFAULT 0,
	"var-req-maior" numeric(17,2) DEFAULT 0,
	"var-rep" numeric(17,2) DEFAULT 0 NOT NULL,
	"var-transf" numeric(17,2) DEFAULT 0 NOT NULL,
	"qt-max-ordem" numeric(19,4) DEFAULT 0,
	"var-mob-maior" numeric(17,2) DEFAULT 0,
	"var-mob-menor" numeric(17,2) DEFAULT 0,
	"sit-aloc" integer DEFAULT 1,
	"cod-localiz" varchar(20),
	"cod-lista-destino" varchar(16),
	"log-atualiz-via-mmp" bit DEFAULT 0,
	"cod-taxa" integer DEFAULT 0,
	"conv-tempo-seg" bit DEFAULT 0,
	"char-1" varchar(400),
	"char-2" varchar(400),
	"dec-1" numeric(23,8) DEFAULT 0,
	"dec-2" numeric(23,8) DEFAULT 0,
	"int-1" integer DEFAULT 0,
	"int-2" integer DEFAULT 0,
	"log-1" bit DEFAULT 0,
	"log-2" bit DEFAULT 0,
	"data-1" date DEFAULT NULL,
	"data-2" date DEFAULT NULL,
	"nivel-apr-requis" integer DEFAULT 0,
	"nivel-apr-solic" integer DEFAULT 0,
	"nivel-apr-manut" integer DEFAULT 0,
	"nivel-apr-compra" integer DEFAULT 0,
	"ind-prev-demanda" integer DEFAULT 1 NOT NULL,
	"ind-calc-meta" integer DEFAULT 1,
	"log-utiliza-batch-padrao" bit DEFAULT 0 NOT NULL,
	"qtd-batch-padrao" numeric(19,4) DEFAULT 1 NOT NULL,
	"check-sum" varchar(40),
	"reporte-ggf" integer DEFAULT 1 NOT NULL,
	"ind-refugo" integer DEFAULT 1 NOT NULL,
	"ind-lista-mrp" integer DEFAULT 1,
	"num-id-familia" integer DEFAULT 0 NOT NULL,
	"cod-classe-frete" varchar(10) NOT NULL,
	"pto-repos" numeric(19,4) DEFAULT 0,
	"cod-reabast" varchar(20),
	"Qtd-min-reabast" numeric(17,2) DEFAULT 0,
	"Cod-var-tempo-res" varchar(8),
	"Qtd-var-ressup" numeric(17,2) DEFAULT 0,
	"cod-grupo-compra-p" varchar(24),
	"cod-grupo-compra-o" varchar(24),
	"cdn-tipo-rec-desp" integer DEFAULT 0,
	"cdn-nat-desp" integer DEFAULT 0,
	"politica-aps" integer DEFAULT 0,
	"geracao-ordem" integer DEFAULT 0,
	"cons-produto" bit DEFAULT 0,
	"cons-saldo" bit DEFAULT 1,
	"mp-restrit" bit DEFAULT 0,
	"qtde-max" numeric(19,4) DEFAULT 0,
	"qtde-fixa" numeric(19,4) DEFAULT 0,
	"lote-repos" numeric(17,2) DEFAULT 0,
	"cons-consumo" bit DEFAULT 0,
	"cod-malha" varchar(10) DEFAULT '0',
	"cod-pulmao" varchar(10),
	"tipo-formula" integer DEFAULT 1 NOT NULL,
	"per-ppm" numeric(19,4) DEFAULT 100,
	"log-control-estoq-refugo" bit DEFAULT 0,
	"log-refugo-preco-fisc" bit DEFAULT 0,
	"cod-item-refugo" varchar(32),
	"val-relac-refugo-item" numeric(20,5) DEFAULT 0,
	"log-multi-malha" bit DEFAULT 0,
	"idi-classif-item" integer DEFAULT 1,
	"log-orig-ext" bit DEFAULT 0,
	"log-altera-valid-lote" bit DEFAULT 0,
	"log-inspec-lote" bit DEFAULT 0,
	"dsl-formul-quant-cq" varchar(500),
	"log-rotei-pend" bit DEFAULT 0,
	CONSTRAINT codigo PRIMARY KEY ("fm-codigo")
);
CREATE INDEX "ch-malha" ON PUB.familia ("cod-malha");
CREATE INDEX comprador ON PUB.familia ("cod-comprado","fm-codigo");
CREATE INDEX "familia-refugo" ON PUB.familia ("cod-item-refugo");
CREATE INDEX planejador ON PUB.familia ("cd-planejado","fm-codigo");


-- PUB."it-nota-fisc" definição

-- Drop table

-- DROP TABLE PUB."it-nota-fisc";

CREATE TABLE PUB."it-nota-fisc" (
	"cod-estabel" varchar(10) NOT NULL,
	serie varchar(10) DEFAULT U NOT NULL,
	"nr-nota-fis" varchar(32) NOT NULL,
	"nr-seq-fat" integer DEFAULT 0 NOT NULL,
	"it-codigo" varchar(32) NOT NULL,
	"peso-liq-fat" numeric(20,5) DEFAULT 0 NOT NULL,
	"peso-bruto" numeric(20,5) DEFAULT 0 NOT NULL,
	"qt-faturada" varchar(56) DEFAULT '0' NOT NULL,
	"un-fatur" varchar(12) NOT NULL,
	"vl-pretab" numeric(25,10) DEFAULT 0 NOT NULL,
	"vl-preori" numeric(25,10) DEFAULT 0 NOT NULL,
	"vl-preuni" numeric(25,10) DEFAULT 0 NOT NULL,
	"vl-merc-tab" numeric(25,10) DEFAULT 0 NOT NULL,
	"vl-merc-ori" numeric(25,10) DEFAULT 0 NOT NULL,
	"vl-merc-liq" numeric(25,10) DEFAULT 0 NOT NULL,
	"vl-tot-item" numeric(25,10) DEFAULT 0,
	"per-des-item" numeric(20,5) DEFAULT 0 NOT NULL,
	"nr-ordem" integer DEFAULT 0,
	parcela integer DEFAULT 0,
	"ind-imp-desc" integer DEFAULT 1 NOT NULL,
	"baixa-estoq" bit DEFAULT 0 NOT NULL,
	"tipo-con-est" integer DEFAULT 1 NOT NULL,
	"cod-depos" varchar(6) NOT NULL,
	"nat-operacao" varchar(12) NOT NULL,
	"cd-trib-ipi" integer DEFAULT 1,
	"aliquota-ipi" numeric(17,2) DEFAULT 0 NOT NULL,
	"perc-red-ipi" numeric(17,2) DEFAULT 0 NOT NULL,
	"cd-trib-iss" integer DEFAULT 1 NOT NULL,
	"aliquota-ISS" numeric(17,2) DEFAULT NULL,
	"cd-trib-icm" integer DEFAULT 1 NOT NULL,
	"aliquota-icm" numeric(17,2) DEFAULT 0 NOT NULL,
	"perc-red-icm" numeric(19,4) DEFAULT 0,
	"atual-estat" bit DEFAULT 1 NOT NULL,
	"vl-despes-it" numeric(17,2) DEFAULT 0 NOT NULL,
	"vl-bicms-it" numeric(17,2) DEFAULT 0,
	"vl-icms-it" numeric(17,2) DEFAULT 0,
	"vl-icmsnt-it" numeric(17,2) DEFAULT 0,
	"vl-icmsou-it" numeric(17,2) DEFAULT 0,
	"vl-bipi-it" numeric(17,2) DEFAULT 0,
	"vl-ipi-it" numeric(17,2) DEFAULT 0 NOT NULL,
	"vl-ipint-it" numeric(17,2) DEFAULT 0 NOT NULL,
	"vl-ipiou-it" numeric(17,2) DEFAULT 0 NOT NULL,
	"vl-biss-it" numeric(17,2) DEFAULT 0 NOT NULL,
	"vl-iss-it" numeric(17,2) DEFAULT 0 NOT NULL,
	"vl-issnt-it" numeric(17,2) DEFAULT 0 NOT NULL,
	"vl-issou-it" numeric(17,2) DEFAULT 0 NOT NULL,
	"vl-bsubs-it" numeric(17,2) DEFAULT 0 NOT NULL,
	"vl-icmsub-it" numeric(17,2) DEFAULT 0 NOT NULL,
	"manut-icm-it" bit DEFAULT 0 NOT NULL,
	"manut-ipi-it" bit DEFAULT 0 NOT NULL,
	"nr-pedido" integer DEFAULT 0 NOT NULL,
	"vl-reajuste" numeric(17,2) DEFAULT 0 NOT NULL,
	"vl-cuscontab" numeric(25,10) DEFAULT 0 NOT NULL,
	"tipo-contr" integer DEFAULT 1 NOT NULL,
	"vl-precon" numeric(25,10) DEFAULT 0 NOT NULL,
	"perc-red-iss" numeric(17,2) DEFAULT 0 NOT NULL,
	"ind-icm-ret" bit DEFAULT 0,
	"ct-cuscon" varchar(40) NOT NULL,
	"sc-cuscon" varchar(40) NOT NULL,
	"ct-cusven" varchar(40) NOT NULL,
	"sc-cusven" varchar(40) NOT NULL,
	"ind-imprenda" bit DEFAULT 0 NOT NULL,
	"vl-irf-it" numeric(17,2) DEFAULT 0 NOT NULL,
	"vl-merc-sicm" numeric(25,10) DEFAULT 0 NOT NULL,
	"no-ab-vend" varchar(24) NOT NULL,
	"nr-ord-produ" integer DEFAULT 0 NOT NULL,
	"dt-retorno" date DEFAULT NULL,
	"cd-vendedor" varchar(24) NOT NULL,
	"dt-cancela" date DEFAULT NULL,
	"dt-confirma" date DEFAULT NULL,
	"dt-emis-nota" date DEFAULT sysdate NOT NULL,
	"codigo-rejei" integer DEFAULT 0 NOT NULL,
	"desc-devol" varchar(4000) NOT NULL,
	"nr-ficha-cq" integer DEFAULT 0 NOT NULL,
	"per-des-icms" numeric(20,5) DEFAULT 0 NOT NULL,
	"tipo-atend" integer DEFAULT 1,
	"ind-componen" integer DEFAULT 1 NOT NULL,
	"vl-ir-adic" numeric(17,2) DEFAULT 0 NOT NULL,
	"class-fiscal" varchar(20) NOT NULL,
	"ind-sit-nota" integer DEFAULT 1 NOT NULL,
	"cod-servico" integer DEFAULT 0 NOT NULL,
	"vl-finsocial" numeric(17,2) DEFAULT 0 NOT NULL,
	"vl-pis" numeric(17,2) DEFAULT 0 NOT NULL,
	"nr-nota-ant" varchar(32),
	"serie-ant" varchar(10) DEFAULT U,
	"cod-refer" varchar(16),
	"nr-seq-ped" integer DEFAULT 0,
	"nr-pedcli" varchar(24),
	"nome-ab-cli" varchar(24),
	"vl-pretab-e" varchar(108) DEFAULT '0',
	"vl-preori-e" varchar(108) DEFAULT '0',
	"vl-preuni-e" varchar(108) DEFAULT '0',
	"vl-merctab-e" varchar(102) DEFAULT '0',
	"vl-mercori-e" varchar(102) DEFAULT '0',
	"vl-mercliq-e" varchar(102) DEFAULT '0',
	"vl-totitem-e" varchar(102) DEFAULT '0',
	"vl-despesit-e" varchar(102) DEFAULT '0',
	"vl-bicmsit-e" varchar(102) DEFAULT '0',
	"vl-icmsit-e" varchar(102) DEFAULT '0',
	"vl-icmsntit-e" varchar(102) DEFAULT '0',
	"vl-icmsouit-e" varchar(102) DEFAULT '0',
	"vl-bipiit-e" varchar(102) DEFAULT '0',
	"vl-ipiit-e" varchar(102) DEFAULT '0',
	"vl-ipintit-e" varchar(102) DEFAULT '0',
	"vl-ipiouit-e" varchar(102) DEFAULT '0',
	"vl-bissit-e" varchar(102) DEFAULT '0',
	"vl-issit-e" varchar(102) DEFAULT '0',
	"vl-issntit-e" varchar(102) DEFAULT '0',
	"vl-issouit-e" varchar(102) DEFAULT '0',
	"vl-bsubsit-e" varchar(102) DEFAULT '0',
	"vl-icmsubit-e" varchar(102) DEFAULT '0',
	"vl-reajuste-e" varchar(108) DEFAULT '0',
	"vl-cuscontab-e" varchar(102) DEFAULT '0',
	"vl-precon-e" varchar(108) DEFAULT '0',
	"vl-irfit-e" varchar(102) DEFAULT '0',
	"vl-mercsimc-e" varchar(102) DEFAULT '0',
	"vl-ipi-dev" numeric(17,2) DEFAULT 0 NOT NULL,
	"vl-sub-emp" numeric(17,2) DEFAULT 0,
	"vl-comp-acum" numeric(20,5) DEFAULT 0 NOT NULL,
	"it-nota-fisc" integer DEFAULT 0,
	"fat-retro" bit DEFAULT 0 NOT NULL,
	"vl-icmscomp-it" numeric(17,2) DEFAULT 0,
	"vl-icmscmp-it-e" varchar(102) DEFAULT '0',
	"cod-est-ven" varchar(10) NOT NULL,
	"nr-entrega" integer DEFAULT 0 NOT NULL,
	"cd-sit-desp" integer DEFAULT 1 NOT NULL,
	"cd-emitente" integer DEFAULT 0,
	"nat-docum" varchar(12),
	"nivel-restituicao" varchar(2),
	"nr-docum" varchar(32),
	"pc-restituicao" numeric(17,2) DEFAULT 0,
	"serie-docum" varchar(10),
	"nr-ord-prod" integer DEFAULT 0,
	"ind-fat-qtfam" bit DEFAULT 0,
	"vl-preuni-zfm" numeric(25,10) DEFAULT 0,
	"vl-merc-liq-zfm" numeric(25,10) DEFAULT 0,
	"conh-frete" varchar(16),
	"emite-duplic" bit DEFAULT 0 NOT NULL,
	"aliquota-tax" numeric(17,2) DEFAULT 0,
	"cod-vat" integer DEFAULT 0,
	"cod-tax" integer DEFAULT 0,
	"vl-iva-it" numeric(17,2) DEFAULT 0,
	"vl-biva-it" numeric(17,2) DEFAULT 0,
	"referencia-ct" varchar(24),
	"cod-localiz" varchar(20),
	"qt-devolvida" varchar(56) DEFAULT '0',
	"vl-frete-it" numeric(17,2) DEFAULT 0,
	"char-1" varchar(200),
	"char-2" varchar(200),
	"dec-1" numeric(23,8) DEFAULT 0,
	"dec-2" numeric(23,8) DEFAULT 0,
	"int-1" integer DEFAULT 0,
	"int-2" integer DEFAULT 0,
	"log-1" bit DEFAULT 0,
	"log-2" bit DEFAULT 0,
	"data-1" date DEFAULT NULL,
	"data-2" date DEFAULT NULL,
	"vl-desconto" numeric(25,10) DEFAULT 0,
	"nr-remito" varchar(32),
	"check-sum" varchar(40),
	"log-usa-tabela-desconto" bit DEFAULT 1 NOT NULL,
	"val-pct-desconto-tab-preco" numeric(25,10) DEFAULT 0 NOT NULL,
	"des-pct-desconto-inform" varchar(100),
	"val-desconto-inform" numeric(25,10) DEFAULT 0 NOT NULL,
	"val-pct-desconto-total" numeric(25,10) DEFAULT 0 NOT NULL,
	"val-pct-desconto-periodo" numeric(25,10) DEFAULT 0,
	"val-pct-desconto-prazo" numeric(25,10) DEFAULT 0,
	"val-desconto-total" numeric(25,10) DEFAULT 0,
	"val-desconto" varchar(180) DEFAULT '0',
	"nr-tabpre" varchar(16) NOT NULL,
	"vl-pretab-me" numeric(25,10) DEFAULT 0 NOT NULL,
	"vl-preori-me" numeric(25,10) DEFAULT 0 NOT NULL,
	"vl-preuni-me" numeric(25,10) DEFAULT 0 NOT NULL,
	"vl-merc-tab-me" numeric(25,10) DEFAULT 0 NOT NULL,
	"vl-merc-ori-me" numeric(25,10) DEFAULT 0 NOT NULL,
	"vl-merc-liq-me" numeric(25,10) DEFAULT 0 NOT NULL,
	"vl-tot-item-me" numeric(25,10) DEFAULT 0,
	"vl-despes-it-me" numeric(20,5) DEFAULT 0 NOT NULL,
	"vl-reajuste-me" numeric(20,5) DEFAULT 0 NOT NULL,
	"vl-cuscontab-me" numeric(25,10) DEFAULT 0 NOT NULL,
	"vl-precon-me" numeric(25,10) DEFAULT 0 NOT NULL,
	"vl-merc-sicm-me" numeric(25,10) DEFAULT 0 NOT NULL,
	"vl-iva-it-me" numeric(20,5) DEFAULT 0,
	"vl-frete-it-me" numeric(20,5) DEFAULT 0,
	"vl-biva-it-me" numeric(20,5) DEFAULT 0,
	"vl-desconto-me" numeric(25,10) DEFAULT 0,
	"ser-remito" varchar(10),
	"nr-seq-it-rmt" integer DEFAULT 0,
	"nr-embarque" integer DEFAULT 0,
	"dec-ftconv-unest" numeric(17,0) DEFAULT 0,
	"num-casa-dec-unest" integer DEFAULT 0,
	"ind-origem-fator" integer DEFAULT 2,
	"val-retenc-csll" numeric(20,5) DEFAULT 0 NOT NULL,
	"val-retenc-pis" numeric(20,5) DEFAULT 0 NOT NULL,
	"val-retenc-cofins" numeric(20,5) DEFAULT 0 NOT NULL,
	"idi-forma-calc-pis" integer DEFAULT 1 NOT NULL,
	"idi-forma-calc-cofins" integer DEFAULT 1 NOT NULL,
	"val-unit-pis" numeric(20,5) DEFAULT 0 NOT NULL,
	"val-unit-cofins" numeric(20,5) DEFAULT 0 NOT NULL,
	"log-preco-unid-medid-estoq" bit DEFAULT 1 NOT NULL,
	"vl-preori-un-fat" numeric(20,5) DEFAULT 0,
	"cod-unid-negoc" varchar(6),
	"val-sat" numeric(20,5) DEFAULT 0 NOT NULL,
	"val-senar" numeric(20,5) DEFAULT 0 NOT NULL,
	"cod-sit-tributar-ipi" varchar(16) NOT NULL,
	"cod-sit-tributar-pis" varchar(16) NOT NULL,
	"cod-sit-tributar-cofins" varchar(16) NOT NULL,
	"idi-modalid-base-icms" integer DEFAULT 1 NOT NULL,
	"idi-modalid-base-ipi" integer DEFAULT 1 NOT NULL,
	"idi-modalid-base-icms-st" integer DEFAULT 1 NOT NULL,
	"num-romaneio" integer DEFAULT 0,
	"val-base-pis-substto" numeric(25,10) DEFAULT 0,
	"val-base-cofins-substto" numeric(25,10) DEFAULT 0,
	"num-seq-roman" integer DEFAULT 0,
	"nat-terc" varchar(12),
	"cod-cta-ctbl-cust-ctbl" varchar(34),
	"cod-cta-ctbl-cust-produt-vendido" varchar(34) NOT NULL,
	"cdd-embarq" numeric(15,0) DEFAULT 0 NOT NULL,
	"val-perc-icms-diferim" numeric(17,2) DEFAULT 0,
	"cod-ord-compra" varchar(30),
	CONSTRAINT "ch-nota-item" PRIMARY KEY ("cod-estabel",serie,"nr-nota-fis","nr-seq-fat","it-codigo")
);
CREATE INDEX "ch-item-data" ON PUB."it-nota-fisc" ("it-codigo","dt-confirma","dt-cancela");
CREATE INDEX "ch-item-nota" ON PUB."it-nota-fisc" ("it-codigo","dt-emis-nota","ind-sit-nota");
CREATE INDEX "ch-natope" ON PUB."it-nota-fisc" ("nat-operacao");
CREATE INDEX "ch-nota-base" ON PUB."it-nota-fisc" ("serie-ant","nr-nota-ant");
CREATE INDEX "ch-nota-docum" ON PUB."it-nota-fisc" ("cod-estabel","serie-docum","nr-docum");
CREATE INDEX "ch-pedcli" ON PUB."it-nota-fisc" ("nome-ab-cli","nr-pedcli","nr-seq-ped","it-codigo","cod-refer","nr-entrega","dt-emis-nota");
CREATE INDEX "ch-pedseq" ON PUB."it-nota-fisc" ("nr-pedido","nr-seq-ped","it-codigo","cod-refer","dt-emis-nota","cod-estabel",serie,"nr-nota-fis");
CREATE INDEX "ch-remito" ON PUB."it-nota-fisc" ("cod-estabel","ser-remito","nr-remito","nr-seq-it-rmt");
CREATE INDEX "itemnf-10" ON PUB."it-nota-fisc" ("nr-tabpre");
CREATE INDEX "itemnf-11" ON PUB."it-nota-fisc" ("cod-estabel",serie,"nr-nota-fis","nr-seq-fat","it-codigo","cod-unid-negoc");
CREATE INDEX "itemnf-12" ON PUB."it-nota-fisc" ("num-romaneio");


-- PUB."natur-oper" definição

-- Drop table

-- DROP TABLE PUB."natur-oper";

CREATE TABLE PUB."natur-oper" (
	"nat-operacao" varchar(12) NOT NULL,
	tipo integer DEFAULT 1,
	denominacao varchar(70) NOT NULL,
	"cd-trib-icm" integer DEFAULT 1 NOT NULL,
	"aliquota-icm" numeric(17,2) DEFAULT 0 NOT NULL,
	"perc-red-icm" numeric(19,4) DEFAULT 0 NOT NULL,
	"cd-trib-ipi" integer DEFAULT 1 NOT NULL,
	"cd-vinc-ipi" varchar(12) DEFAULT NULL,
	"perc-red-ipi" numeric(17,2) DEFAULT 0 NOT NULL,
	"cd-trib-iss" integer DEFAULT 1 NOT NULL,
	"perc-red-iss" numeric(17,2) DEFAULT 0 NOT NULL,
	"emite-duplic" bit DEFAULT 0 NOT NULL,
	"cod-mensagem" integer DEFAULT 0,
	"atual-estat" bit DEFAULT 1 NOT NULL,
	mercado integer DEFAULT 1 NOT NULL,
	"preco-saida" integer DEFAULT 1 NOT NULL,
	"manut-icm" bit DEFAULT 1 NOT NULL,
	"manut-ipi" bit DEFAULT 1 NOT NULL,
	"especie-doc" varchar(6),
	"consum-final" bit DEFAULT 0 NOT NULL,
	"aliq-icm-com" numeric(17,2) DEFAULT 0 NOT NULL,
	"baixa-estoq" bit DEFAULT 0 NOT NULL,
	"perc-PIS" varchar(24) DEFAULT '0' NOT NULL,
	"per-fin-soc" varchar(24) DEFAULT '0' NOT NULL,
	"tp-base-icm" varchar(2) DEFAULT A NOT NULL,
	"ind-imprenda" bit DEFAULT 0 NOT NULL,
	"ct-recven" varchar(40) NOT NULL,
	"sc-recven" varchar(40) NOT NULL,
	"ct-cusven" varchar(40) NOT NULL,
	"sc-cusven" varchar(40) NOT NULL,
	transf bit DEFAULT 0 NOT NULL,
	terceiros bit DEFAULT 0 NOT NULL,
	"cd-situacao" integer DEFAULT 0 NOT NULL,
	"cd-registro" varchar(4) NOT NULL,
	"oper-terc" integer DEFAULT 1 NOT NULL,
	"cod-esp" varchar(4) NOT NULL,
	"modelo-docto" varchar(4) NOT NULL,
	"per-des-icms" numeric(20,5) DEFAULT 0 NOT NULL,
	narrativa varchar(4000) NOT NULL,
	"ind-entfut" bit DEFAULT 0,
	"tp-oper-terc" integer DEFAULT 1 NOT NULL,
	"ind-gera-of" bit DEFAULT 0 NOT NULL,
	"ind-est-crz" bit DEFAULT 0 NOT NULL,
	"ind-est-mof" bit DEFAULT 0 NOT NULL,
	"ind-est-qtd" bit DEFAULT 0 NOT NULL,
	"atualiza-of" bit DEFAULT 1 NOT NULL,
	"nat-comp" varchar(12) NOT NULL,
	"ct-transven" varchar(40) NOT NULL,
	"sc-transven" varchar(40) NOT NULL,
	"auto-ce" bit DEFAULT 1,
	"auto-cr" bit DEFAULT 0,
	"auto-est" bit DEFAULT 1,
	"calc-auto" bit DEFAULT 1,
	"ind-tipo-vat" bit DEFAULT 0 NOT NULL,
	"usa-nota-ent" bit DEFAULT 1,
	"usa-pick" bit DEFAULT 1,
	uso integer DEFAULT 1,
	"subs-trib" bit DEFAULT 0 NOT NULL,
	"tp-rec-desp" integer DEFAULT 0,
	"per-sub-tri" numeric(17,2) DEFAULT 0,
	"ind-contabilizacao" bit DEFAULT 0,
	"nat-vinculada" varchar(12) DEFAULT NULL,
	"icms-subs-trib" numeric(17,2) DEFAULT 0 NOT NULL,
	"ind-it-icms" bit DEFAULT 0,
	"ind-it-sub-dif" bit DEFAULT 0,
	"imp-nota" bit DEFAULT 0,
	"nat-ativa" bit DEFAULT 1 NOT NULL,
	"venda-ativo" bit DEFAULT 0 NOT NULL,
	"ipi-icm-out" bit DEFAULT 0,
	"credito-subs" bit DEFAULT 0,
	"merc-base-icms" integer DEFAULT 1,
	"baixa-ship" bit DEFAULT 0,
	"auto-ct" bit DEFAULT 0,
	"tipo-trib" integer DEFAULT 1,
	"nota-rateio" bit DEFAULT 0,
	"char-1" varchar(200),
	"char-2" varchar(200),
	"dec-1" numeric(23,8) DEFAULT 0,
	"dec-2" numeric(23,8) DEFAULT 0,
	"int-1" integer DEFAULT 0,
	"int-2" integer DEFAULT 0,
	"log-1" bit DEFAULT 0,
	"log-2" bit DEFAULT 0,
	"data-1" date DEFAULT NULL,
	"data-2" date DEFAULT NULL,
	"cod-canal-venda" integer DEFAULT 0,
	"check-sum" varchar(40),
	"log-natureza-bonif" bit DEFAULT 0,
	"cod-natur-oper-bonif" varchar(12),
	"gera-prev-cr" bit DEFAULT 0,
	"alt-vl-it-terc" bit DEFAULT 0,
	"log-acum-ciap" bit DEFAULT 1 NOT NULL,
	"credito-ciap" bit DEFAULT 0,
	"tipo-compra" integer DEFAULT 1 NOT NULL,
	"log-oper-triang" bit DEFAULT 0,
	"ind-venda-ambulante" integer DEFAULT 0,
	"log-nota-comercio" varchar(10),
	"ind-nota-propria" integer DEFAULT 0,
	"var-val-it-terc" numeric(19,4) DEFAULT 0,
	"dest-red-icms" numeric(19,4) DEFAULT 0,
	"log-ipi-bicms" bit DEFAULT 0,
	"log-frete-bipi" bit DEFAULT 0,
	"log-base-ipi" bit DEFAULT 0,
	"log-ipi-out-tot" bit DEFAULT 0,
	"log-biss" bit DEFAULT 0,
	"log-atual-cotas" bit DEFAULT 0,
	"log-vl-it-terc" bit DEFAULT 0,
	"log-emit-remito" bit DEFAULT 0,
	"log-ipi-out-bsubst" bit DEFAULT 0,
	"log-icms-out-subst" bit DEFAULT 0,
	"log-gera-cre-subst" bit DEFAULT 0,
	"log-remito-gera-prevcr" bit DEFAULT 0,
	"perc-desc-zf" numeric(17,2) DEFAULT 0,
	"log-ret-inss-fonte" bit DEFAULT 0,
	"modelo-cupom" varchar(10),
	"form-cfop" varchar(10),
	"ind-entreg-futur" integer DEFAULT 0,
	"ind-situacao" integer DEFAULT 1 NOT NULL,
	"log-impr-nf-auto" bit DEFAULT 0,
	"ind-devolucao-valor" bit DEFAULT 0,
	"Log-picking" bit DEFAULT 0 NOT NULL,
	"cod-trib-ii" integer DEFAULT 0,
	"log-impres-autom" bit DEFAULT 0,
	"cod-cfop" varchar(20) NOT NULL,
	"cod-livre-1" varchar(200),
	"cod-livre-2" varchar(200),
	"log-livre-1" bit DEFAULT 0,
	"log-livre-2" bit DEFAULT 0,
	"log-livre-3" bit DEFAULT 0,
	"log-livre-4" bit DEFAULT 0,
	"log-livre-5" bit DEFAULT 0,
	"log-livre-6" bit DEFAULT 0,
	"num-livre-1" integer DEFAULT 0,
	"num-livre-2" integer DEFAULT 0,
	"val-livre-1" numeric(23,8) DEFAULT 0,
	"val-livre-2" numeric(23,8) DEFAULT 0,
	"dat-livre-1" date DEFAULT NULL,
	"dat-livre-2" date DEFAULT NULL,
	"log-icms-presmdo" bit DEFAULT 0,
	"log-natur-operac-draw" bit DEFAULT 0,
	"cdd-perc-retenc-csll" numeric(17,2) DEFAULT 0 NOT NULL,
	"cdd-perc-retenc-pis" numeric(17,2) DEFAULT 0 NOT NULL,
	"cdd-perc-retenc-cofins" numeric(17,2) DEFAULT 0 NOT NULL,
	"val-perc-impto-renda" numeric(17,2) DEFAULT 0,
	"log-ipi-contrib-social" bit DEFAULT 0 NOT NULL,
	"log-ipi-outras-contrib-social" bit DEFAULT 0 NOT NULL,
	"log-suspens-impto-import" bit DEFAULT 0,
	"log-suspens-ipi-import" bit DEFAULT 0,
	"log-memorando" bit DEFAULT 0 NOT NULL,
	"log-ipi-contrib-retid" bit DEFAULT 0 NOT NULL,
	"log-ipi-outras-contrib-retid" bit DEFAULT 0 NOT NULL,
	"log-icms-substto-repas" bit DEFAULT 0 NOT NULL,
	"log-icms-substto-compltar" bit DEFAULT 0 NOT NULL,
	"val-perc-desc-pis-zfm" numeric(20,5) DEFAULT 0 NOT NULL,
	"val-perc-desc-cofins-zfm" numeric(20,5) DEFAULT 0 NOT NULL,
	"log-deduz-desc-zfm-tot-nf" bit DEFAULT 0,
	"val-perc-sat" numeric(17,2) DEFAULT 0 NOT NULL,
	"val-perc-senar" numeric(17,2) DEFAULT 0 NOT NULL,
	"log-apurac-retenc" bit DEFAULT 0 NOT NULL,
	"cod-model-nf-eletro" varchar(16) NOT NULL,
	"log-icms-substto-base-contrib" bit DEFAULT 0 NOT NULL,
	"log-icms-substto-base-irf-retid" bit DEFAULT 0 NOT NULL,
	"cod-natur-ref" varchar(12),
	"log-vda-ret" bit DEFAULT 0,
	"log-gera-ncredito" bit DEFAULT 0,
	"log-permite-lote-vencid" bit DEFAULT 0,
	"idi-tip-devol-consig" integer DEFAULT 0 NOT NULL,
	"log-icms-despes-import" bit DEFAULT 0,
	"log-pis-despes-import" bit DEFAULT 0,
	"log-cofins-despes-import" bit DEFAULT 0,
	"log-icms-despes-import-nfr" bit DEFAULT 0,
	"log-incid-icms-tot-nfr" bit DEFAULT 0,
	"log-integr-base-calc-icms-nfr" bit DEFAULT 0,
	"log-icms-substto-antecip" bit DEFAULT 0 NOT NULL,
	"log-consid-icms-outras" bit DEFAULT 0,
	"log-cr-st-antec" bit DEFAULT 0 NOT NULL,
	"log-contrib-st-antec" bit DEFAULT 0 NOT NULL,
	"log-impr-ipi-danfe" bit DEFAULT 0 NOT NULL,
	"log-ipi-nao-tributad" bit DEFAULT 0 NOT NULL,
	"log-ipi-imune" bit DEFAULT 0 NOT NULL,
	"idi-escrit-fatur-remes" integer DEFAULT 1 NOT NULL,
	"cod-cta-ctbl-cust-vda" varchar(34) NOT NULL,
	"cod-cta-ctbl-recta-vendas" varchar(34) NOT NULL,
	"cod-cta-ctbl-transit-vendas" varchar(34) NOT NULL,
	"log-operac-transp" bit DEFAULT 0,
	"log-ipi-suspen-icms" bit DEFAULT 0,
	"log-nfse-nacional" bit DEFAULT 0,
	CONSTRAINT natureza PRIMARY KEY ("nat-operacao")
);


-- PUB."nota-fiscal" definição

-- Drop table

-- DROP TABLE PUB."nota-fiscal";

CREATE TABLE PUB."nota-fiscal" (
	"cod-estabel" varchar(10) NOT NULL,
	serie varchar(10) DEFAULT U NOT NULL,
	"nr-nota-fis" varchar(32) NOT NULL,
	"nome-ab-cli" varchar(24) NOT NULL,
	"dt-emis-nota" date DEFAULT sysdate NOT NULL,
	"ind-sit-nota" integer DEFAULT 1 NOT NULL,
	"dt-confirma" date DEFAULT NULL,
	"hr-confirma" varchar(10) NOT NULL,
	"dt-cancela" date DEFAULT NULL,
	"desc-cancela" varchar(4000) NOT NULL,
	"hr-atualiza" varchar(10) NOT NULL,
	"cod-cond-pag" integer DEFAULT 0 NOT NULL,
	"nr-pedcli" varchar(24) NOT NULL,
	"cod-entrega" varchar(24) NOT NULL,
	endereco varchar(80) NOT NULL,
	bairro varchar(60) NOT NULL,
	cidade varchar(50) NOT NULL,
	estado varchar(8) NOT NULL,
	cep varchar(24) NOT NULL,
	pais varchar(40) DEFAULT Brasil NOT NULL,
	cgc varchar(38),
	"ins-estadual" varchar(38) NOT NULL,
	"perc-desco1" numeric(18,3) DEFAULT 0,
	"perc-desco2" numeric(18,3) DEFAULT 0,
	"cond-redespa" varchar(4000) NOT NULL,
	"cidade-cif" varchar(50),
	"cod-des-merc" integer DEFAULT 1,
	"nome-transp" varchar(24),
	"tp-preco" integer DEFAULT 1 NOT NULL,
	"cod-rota" varchar(24) NOT NULL,
	"ind-lib-nota" bit DEFAULT 0,
	"nr-tabpre" varchar(16) NOT NULL,
	"vl-tot-nota" numeric(25,10) DEFAULT 0 NOT NULL,
	"vl-mercad" numeric(25,10) DEFAULT 0 NOT NULL,
	"vl-frete" numeric(17,2) DEFAULT 0,
	"vl-seguro" numeric(17,2) DEFAULT 0,
	"vl-embalagem" numeric(17,2) DEFAULT 0,
	"nr-praz-med" numeric(17,2) DEFAULT 0,
	"nr-fatura" varchar(32),
	"nat-operacao" varchar(12) NOT NULL,
	"emite-duplic" bit DEFAULT 0 NOT NULL,
	"cod-mensagem" integer DEFAULT 0,
	"preco-saida" integer DEFAULT 1 NOT NULL,
	"marca-volume" varchar(40) NOT NULL,
	"nr-volumes" varchar(20),
	"peso-liq-tot" numeric(18,3) DEFAULT 0 NOT NULL,
	"peso-bru-tot" numeric(18,3) DEFAULT 0 NOT NULL,
	"ind-tip-nota" integer DEFAULT 1 NOT NULL,
	"cod-portador" integer DEFAULT 0,
	modalidade integer DEFAULT 0,
	mercado integer DEFAULT 1 NOT NULL,
	"tipo-fat" integer DEFAULT 1 NOT NULL,
	"dt-prvenc" date DEFAULT NULL,
	"observ-nota" varchar(4000),
	"nr-tab-finan" integer DEFAULT 0,
	"nr-ind-finan" integer DEFAULT 0 NOT NULL,
	"ind-contabil" bit DEFAULT 0,
	"dt-at-ofest" date DEFAULT NULL,
	"dt-atual-cr" date DEFAULT NULL,
	placa varchar(20),
	"vl-acum-dup" numeric(17,2) DEFAULT 0 NOT NULL,
	"cod-rep" integer DEFAULT 0 NOT NULL,
	"no-ab-reppri" varchar(24) NOT NULL,
	"nome-ab-reg" varchar(24) NOT NULL,
	"esp-docto" integer DEFAULT 1 NOT NULL,
	distancia numeric(16,1) DEFAULT 0 NOT NULL,
	"cd-vendedor" varchar(24) NOT NULL,
	"dt-saida" date DEFAULT NULL,
	"taxa-orig" numeric(20,5) DEFAULT 0 NOT NULL,
	"user-calc" varchar(24),
	"taxa-real" numeric(20,5) DEFAULT 0 NOT NULL,
	"per-des-icms" numeric(18,3) DEFAULT 0 NOT NULL,
	"nr-embarque" integer DEFAULT 0,
	"tp-pedido" varchar(4),
	"nome-tr-red" varchar(24),
	"cod-emitente" integer DEFAULT 0,
	"vl-taxa-exp" numeric(23,8) DEFAULT 0,
	"nr-proc-exp" varchar(24),
	"vl-totnota-e" varchar(108) DEFAULT '0',
	"vl-mercad-e" varchar(108) DEFAULT '0',
	"vl-frete-e" varchar(108) DEFAULT '0',
	"vl-seguro-e" varchar(108) DEFAULT '0',
	"vl-embalagem-e" varchar(108) DEFAULT '0',
	"vl-acumdup-e" varchar(108) DEFAULT '0',
	"vl-taxaexp-e" varchar(72) DEFAULT '0',
	identific varchar(24) NOT NULL,
	"cod-dep-ext" varchar(6),
	"fat-retro" bit DEFAULT 0 NOT NULL,
	"vl-fatura" numeric(17,2) DEFAULT 0,
	"docto-orig" varchar(32),
	descto2 numeric(17,2) DEFAULT 0,
	descto1 numeric(17,2) DEFAULT 0,
	"nr-fat-retro" varchar(32) NOT NULL,
	"dt-entr-cli" date DEFAULT NULL,
	"cd-sit-desp" integer DEFAULT 1 NOT NULL,
	"hr-entr-cli" varchar(16) DEFAULT NULL,
	"nivel-restituicao" varchar(2),
	"nr-parcelas" integer DEFAULT 1,
	"nr-resumo" integer DEFAULT 0,
	"pc-restituicao" numeric(17,2) DEFAULT 0,
	"vl-tot-itens-fat" numeric(17,2) DEFAULT 0,
	"uf-placa" varchar(4),
	"invoice-id" varchar(2) NOT NULL,
	"vl-tot-com" numeric(17,2) DEFAULT 0,
	"vl-comis-nota" numeric(17,2) DEFAULT 0,
	"zip-code" varchar(24),
	"serie-ant" varchar(10) DEFAULT U,
	"nr-nota-ant" varchar(32),
	"dt-embarque" date DEFAULT sysdate,
	"mo-codigo" varchar(32),
	"nr-pedido-nf-orig" integer DEFAULT 0,
	"replica-nf" bit DEFAULT 0,
	"dt-at-est" date DEFAULT NULL,
	"cod-tax" integer DEFAULT 0,
	"tax-desp" numeric(17,2) DEFAULT 0,
	"tax-frete" numeric(17,2) DEFAULT 0,
	"vl-tot-ipi" numeric(17,2) DEFAULT 0,
	"vl-tot-iva" numeric(17,2) DEFAULT 0,
	"caixa-postal" varchar(20),
	"serie-orig" varchar(10),
	"nro-nota-orig" varchar(32),
	"cn-codigo" varchar(80),
	"ind-orig-entrada" integer DEFAULT 1,
	"ind-via-envio" integer DEFAULT 1,
	"nro-proc-entrada" integer DEFAULT 0,
	"nro-proc-saida" integer DEFAULT 0,
	"dt-at-ct" date DEFAULT NULL,
	"refer-ct" varchar(24),
	"vl-merc-tot-fat" numeric(25,10) DEFAULT 0,
	"char-1" varchar(4000),
	"char-2" varchar(4000),
	"dec-1" numeric(23,8) DEFAULT 0,
	"dec-2" numeric(23,8) DEFAULT 0,
	"int-1" integer DEFAULT 0,
	"int-2" integer DEFAULT 0,
	"log-1" bit DEFAULT 0,
	"log-2" bit DEFAULT 0,
	"data-1" date DEFAULT NULL,
	"data-2" date DEFAULT NULL,
	"cod-canal-venda" integer DEFAULT 0,
	"vl-desconto" numeric(17,2) DEFAULT 0,
	"cod-imagem" varchar(60),
	"check-sum" varchar(40),
	"log-usa-tabela-desconto" bit DEFAULT 1 NOT NULL,
	"val-pct-desconto-tab-preco" numeric(25,10) DEFAULT 0 NOT NULL,
	"des-pct-desconto-inform" varchar(100),
	"val-pct-desconto-total" numeric(25,10) DEFAULT 0 NOT NULL,
	"val-desconto-total" numeric(25,10) DEFAULT 0,
	"vl-tot-nota-me" numeric(25,10) DEFAULT 0 NOT NULL,
	"vl-mercad-me" numeric(25,10) DEFAULT 0 NOT NULL,
	"vl-frete-me" numeric(20,5) DEFAULT 0,
	"vl-seguro-me" numeric(20,5) DEFAULT 0,
	"vl-embalagem-me" numeric(20,5) DEFAULT 0 NOT NULL,
	"vl-acum-dup-me" numeric(20,5) DEFAULT 0 NOT NULL,
	"vl-fatura-me" numeric(20,5) DEFAULT 0,
	"vl-tot-itens-fat-me" numeric(20,5) DEFAULT 0,
	"vl-tot-com-me" numeric(20,5) DEFAULT 0,
	"vl-comis-nota-me" numeric(20,5) DEFAULT 0,
	"vl-tot-iva-me" numeric(20,5) DEFAULT 0,
	"vl-merc-tot-fat-me" numeric(25,10) DEFAULT 0,
	"vl-desconto-me" numeric(20,5) DEFAULT 0,
	"vl-cotacao-fatur" numeric(20,5) DEFAULT 0,
	"vl-cotacao-pedido" numeric(20,5) DEFAULT 0,
	"dt-atual-ap" date DEFAULT NULL,
	"nr-siscomex" varchar(40),
	"cod-tax-fre" integer DEFAULT 0,
	"cod-tax-div" integer DEFAULT 0,
	"perc-tax-fre" numeric(17,2) DEFAULT 0,
	"perc-tax-div" numeric(17,2) DEFAULT 0,
	"nr-invoice" varchar(32) NOT NULL,
	"val-pct-desconto-valor" numeric(25,10) DEFAULT 0 NOT NULL,
	"ind-tp-frete" integer DEFAULT 1,
	"tax-emb" numeric(17,2) DEFAULT 0,
	"tax-emb-me" numeric(20,5) DEFAULT 0,
	"tax-seg" numeric(17,2) DEFAULT 0,
	"tax-seg-me" numeric(20,5) DEFAULT 0,
	"tax-fre-me" numeric(20,5) DEFAULT 0,
	"tax-div-me" numeric(20,5) DEFAULT 0,
	"perc-tax-emb" numeric(17,2) DEFAULT 0,
	"perc-tax-seg" numeric(17,2) DEFAULT 0,
	"cod-tax-emb" integer DEFAULT 0,
	"cod-tax-seg" integer DEFAULT 0,
	"nome-abrev-tri" varchar(24),
	endereco_text varchar(4000),
	"refer-cr" varchar(24),
	"desc-valor-ped" numeric(20,5) DEFAULT 0,
	"desc-valor-nota" numeric(20,5) DEFAULT 0,
	"val-desp-outros" numeric(20,5) DEFAULT 0,
	"val-desp-outros-inf" numeric(20,5) DEFAULT 0,
	"num-rma-orig" varchar(32),
	"log-estorn-comis-repres" bit DEFAULT 0,
	"cod-rma" varchar(32),
	"obs-gerada" varchar(4000),
	"cod-estab-estoq" varchar(10),
	"tab-ind-fin" numeric(20,5) DEFAULT 1,
	"log-juros-prorate" bit DEFAULT 0 NOT NULL,
	"log-possui-retenc" bit DEFAULT 0 NOT NULL,
	"val-desc-pis-zfm" numeric(20,5) DEFAULT 0,
	"val-desc-cofins-zfm" numeric(20,5) DEFAULT 0,
	"idi-sit-nf-eletro" integer DEFAULT 1 NOT NULL,
	"cod-chave-aces-nf-eletro" varchar(120),
	"idi-forma-emis-nf-eletro" integer DEFAULT 1 NOT NULL,
	"des-espec-volum" varchar(120) NOT NULL,
	"cod-placa-2" varchar(16) NOT NULL,
	"cod-uf-placa-2" varchar(16) NOT NULL,
	"cod-lacre" varchar(244),
	"val-iof" numeric(17,2) DEFAULT 0,
	"cod-protoc" varchar(30),
	"num-romaneio" integer DEFAULT 0,
	"cod-usuar-contingen-nf-eletro" varchar(24),
	"cod-estab-proces-export" varchar(10) NOT NULL,
	"hra-emis-nf" varchar(16),
	"dt-atualiza" date DEFAULT NULL,
	"hra-atualiz" varchar(16) DEFAULT '000000',
	"cod-safra" varchar(18) DEFAULT '00000000',
	"num-cx-financ" integer DEFAULT 0,
	"num-process-negoc" integer DEFAULT 0,
	"cdd-embarq" numeric(15,0) DEFAULT 0 NOT NULL,
	"log-var-cambial" bit DEFAULT 1,
	CONSTRAINT "ch-nota" PRIMARY KEY ("cod-estabel",serie,"nr-nota-fis")
);
CREATE INDEX "ch-atual-cr" ON PUB."nota-fiscal" ("dt-atual-cr","cod-emitente");
CREATE INDEX "ch-clinota" ON PUB."nota-fiscal" ("nome-ab-cli","dt-emis-nota","ind-sit-nota");
CREATE INDEX "ch-condpag" ON PUB."nota-fiscal" ("cod-cond-pag");
CREATE INDEX "ch-distancia" ON PUB."nota-fiscal" ("dt-emis-nota","ind-sit-nota","nome-transp");
CREATE INDEX "ch-embarque" ON PUB."nota-fiscal" ("cdd-embarq","nr-embarque");
CREATE INDEX "ch-emi-nota" ON PUB."nota-fiscal" ("cod-emitente","dt-emis-nota","ind-sit-nota");
CREATE INDEX "ch-fatura" ON PUB."nota-fiscal" ("cod-estabel",serie,"nr-fatura");
CREATE INDEX "ch-invoice" ON PUB."nota-fiscal" ("nr-proc-exp","invoice-id");
CREATE INDEX "ch-nome-abrev" ON PUB."nota-fiscal" ("nome-ab-cli","cod-estabel",serie,"nr-nota-fis");
CREATE INDEX "ch-nome-repres" ON PUB."nota-fiscal" ("no-ab-reppri","cod-estabel",serie,"nr-nota-fis");
CREATE INDEX "ch-nota-base" ON PUB."nota-fiscal" ("serie-ant","nr-nota-ant");
CREATE INDEX "ch-pedido" ON PUB."nota-fiscal" ("nome-ab-cli","nr-pedcli");
CREATE INDEX "ch-portador" ON PUB."nota-fiscal" ("cod-portador",modalidade);
CREATE INDEX "ch-reg-rep" ON PUB."nota-fiscal" ("nome-ab-reg","no-ab-reppri","dt-emis-nota","ind-sit-nota");
CREATE INDEX "ch-rota" ON PUB."nota-fiscal" ("cod-rota","cod-estabel",serie);
CREATE INDEX "ch-sit-nota" ON PUB."nota-fiscal" ("dt-emis-nota","ind-sit-nota","dt-confirma");
CREATE INDEX "ch-tabfin" ON PUB."nota-fiscal" ("nr-tab-finan");
CREATE INDEX "ch-tabpre" ON PUB."nota-fiscal" ("nr-tabpre");
CREATE INDEX "ch-transp" ON PUB."nota-fiscal" ("nome-transp");
CREATE INDEX natoper ON PUB."nota-fiscal" ("nat-operacao");
CREATE INDEX "nfftrm-20" ON PUB."nota-fiscal" ("dt-emis-nota","cod-estabel",serie,"nr-nota-fis");
CREATE INDEX "nfftrm-21" ON PUB."nota-fiscal" ("cod-estabel","serie-orig","nro-nota-orig");
CREATE INDEX "nfftrm-22" ON PUB."nota-fiscal" ("num-rma-orig");
CREATE INDEX "nfftrm-23" ON PUB."nota-fiscal" ("dt-confirma","dt-cancela","cod-estabel","dt-emis-nota");
CREATE INDEX "nfftrm-24" ON PUB."nota-fiscal" ("nome-tr-red");
CREATE INDEX "nfftrm-25" ON PUB."nota-fiscal" ("idi-sit-nf-eletro","dt-emis-nota","cod-estabel",serie,"nr-nota-fis");
CREATE INDEX "nfftrm-26" ON PUB."nota-fiscal" ("num-romaneio");
CREATE INDEX "nfftrm-27" ON PUB."nota-fiscal" ("dt-atualiza","hra-atualiz");


-- PUB."ped-item" definição

-- Drop table

-- DROP TABLE PUB."ped-item";

CREATE TABLE PUB."ped-item" (
	"nome-abrev" varchar(24) NOT NULL,
	"nr-pedcli" varchar(24) NOT NULL,
	"nr-sequencia" integer DEFAULT 0 NOT NULL,
	"it-codigo" varchar(32) NOT NULL,
	"nr-ordem" integer DEFAULT 0,
	parcela integer DEFAULT 0,
	"dt-entorig" date DEFAULT sysdate,
	"dt-entrega" date DEFAULT sysdate NOT NULL,
	"dt-canseq" date DEFAULT NULL,
	"desc-cancela" varchar(4000) NOT NULL,
	"dt-reativ" date DEFAULT NULL,
	"dt-suspensao" date DEFAULT NULL,
	"qt-pedida" numeric(19,4) DEFAULT 0 NOT NULL,
	"qt-atendida" numeric(19,4) DEFAULT 0,
	"qt-pendente" numeric(19,4) DEFAULT 0,
	"qt-devolvida" numeric(19,4) DEFAULT 0,
	"dt-devolucao" date DEFAULT NULL,
	"desc-devol" varchar(4000) NOT NULL,
	"vl-pretab" numeric(25,10) DEFAULT 0 NOT NULL,
	"vl-preori" numeric(25,10) DEFAULT 0 NOT NULL,
	"vl-preuni" numeric(25,10) DEFAULT 0 NOT NULL,
	"per-des-item" numeric(21,6) DEFAULT 0,
	"per-minfat" numeric(17,2) DEFAULT 0 NOT NULL,
	"cod-sit-item" integer DEFAULT 1,
	"user-impl" varchar(24),
	"dt-userimp" date DEFAULT NULL,
	"user-alte" varchar(24),
	"dt-useralt" date DEFAULT NULL,
	"user-canc" varchar(24),
	"dt-usercan" date DEFAULT NULL,
	"user-reat" varchar(24),
	"dt-userrea" date DEFAULT NULL,
	"user-devol" varchar(24) NOT NULL,
	"dt-userdev" date DEFAULT NULL,
	"user-susp" varchar(24),
	"dt-usersusp" date DEFAULT NULL,
	"aliquota-ipi" numeric(17,2) DEFAULT 0 NOT NULL,
	"ind-icm-ret" bit DEFAULT 0,
	"vl-merc-abe" numeric(25,10) DEFAULT 0 NOT NULL,
	"vl-liq-it" numeric(25,10) DEFAULT 0 NOT NULL,
	"vl-liq-abe" numeric(25,10) DEFAULT 0 NOT NULL,
	"vl-tot-it" numeric(25,10) DEFAULT 0 NOT NULL,
	"nr-tabpre" varchar(16) NOT NULL,
	"tp-preco" integer DEFAULT 1 NOT NULL,
	"per-des-icms" numeric(20,5) DEFAULT 0,
	"nat-operacao" varchar(12) NOT NULL,
	"tipo-atend" integer DEFAULT 1,
	observacao varchar(4000),
	"ind-componen" integer DEFAULT 1 NOT NULL,
	"qt-fatenf" numeric(19,4) DEFAULT 0 NOT NULL,
	"cod-refer" varchar(16) NOT NULL,
	"qt-transfer" numeric(19,4) DEFAULT 0,
	"desc-txt" varchar(100),
	"qt-alocada" numeric(19,4) DEFAULT 0,
	"cod-sit-pre" integer DEFAULT 1,
	"dt-max-fat" date DEFAULT NULL,
	"tp-aloc-lote" integer DEFAULT 1,
	"dt-min-fat" date DEFAULT sysdate NOT NULL,
	"esp-ped" integer DEFAULT 1 NOT NULL,
	"perc-fornec" numeric(17,2) DEFAULT 0 NOT NULL,
	"qt-lote-min" numeric(19,4) DEFAULT 0 NOT NULL,
	"cd-freq" integer DEFAULT 0 NOT NULL,
	"nr-progcli" varchar(70) DEFAULT NULL,
	"nr-versao" integer DEFAULT 0,
	"cod-entrega" varchar(24) NOT NULL,
	"cd-origem" integer DEFAULT 1 NOT NULL,
	"vl-pauta" numeric(25,10) DEFAULT 0,
	"qt-log-aloca" numeric(19,4) DEFAULT 0,
	"tp-adm-lote" integer DEFAULT 1,
	"ind-fat-qtfam" bit DEFAULT 0,
	"config-alter" bit DEFAULT 0,
	"nr-config" integer DEFAULT 0,
	"cons-mrp" bit DEFAULT 1,
	"cons-pmp" bit DEFAULT 1,
	"nr-ord-produ" integer DEFAULT 0,
	"nr-programa" integer DEFAULT 0,
	"qt-trans-mp" numeric(19,4) DEFAULT 0,
	"log-ordens-emitidas" bit DEFAULT 0,
	"aloca-canc-saldo" bit DEFAULT 0,
	"aliquota-tax" numeric(17,2) DEFAULT 0,
	"cod-isencao" integer DEFAULT 0,
	"cod-tax" integer DEFAULT 0,
	"cod-vat" integer DEFAULT 0,
	"aliquota-iva" numeric(17,2) DEFAULT 0,
	"qt-ordens" numeric(19,4) DEFAULT 0,
	"char-1" varchar(200),
	"char-2" varchar(200),
	"dec-1" numeric(23,8) DEFAULT 0,
	"dec-2" numeric(23,8) DEFAULT 0,
	"int-1" integer DEFAULT 0,
	"int-2" integer DEFAULT 0,
	"log-1" bit DEFAULT 0,
	"log-2" bit DEFAULT 0,
	"data-1" date DEFAULT NULL,
	"data-2" date DEFAULT NULL,
	"vl-desconto" numeric(25,10) DEFAULT 0,
	"cod-cond-esp" integer DEFAULT 0,
	"cod-sit-com" integer DEFAULT 1,
	"motivo-alt-sit-quota" varchar(4000),
	"dat-alter-sit" date DEFAULT sysdate,
	"cod-usu-alt-sit" varchar(24),
	"check-sum" varchar(40),
	"log-usa-tabela-desconto" bit DEFAULT 1 NOT NULL,
	"val-pct-desconto-tab-preco" numeric(25,10) DEFAULT 0 NOT NULL,
	"des-pct-desconto-inform" varchar(100),
	"val-desconto-inform" numeric(25,10) DEFAULT 0 NOT NULL,
	"val-pct-desconto-total" numeric(25,10) DEFAULT 0 NOT NULL,
	"log-concede-bonif-qtd" bit DEFAULT 0,
	"val-pct-bonif" numeric(25,10) DEFAULT 0,
	"val-pct-desconto-periodo" numeric(25,10) DEFAULT 0,
	"val-pct-desconto-prazo" numeric(25,10) DEFAULT 0,
	"val-desconto-total" numeric(25,10) DEFAULT 0,
	"val-desconto-bonif" numeric(25,10) DEFAULT 0 NOT NULL,
	"num-sequencia-bonif" integer DEFAULT 0 NOT NULL,
	"val-desconto" varchar(180) DEFAULT '0',
	"qt-un-fat" numeric(19,4) DEFAULT 0,
	"vl-preori-un-fat" numeric(25,10) DEFAULT 0,
	"cod-mot-canc-cot" integer DEFAULT 0,
	"user-aprov-cot" varchar(24),
	"dt-aprov-cot" date DEFAULT NULL,
	"user-lib-cot" varchar(24),
	"dt-lib-cot" date DEFAULT NULL,
	"cod-sit-preco" integer DEFAULT 1 NOT NULL,
	"user-preco" varchar(24),
	"dat-aprov-preco" date DEFAULT sysdate,
	"desc-lib-preco" varchar(152),
	endereco_text varchar(4000),
	"des-un-medida" varchar(4) NOT NULL,
	"dec-ftconv-unest" numeric(17,0) DEFAULT 0,
	"ind-origem-fator" integer DEFAULT 2,
	"num-casa-dec-unest" integer DEFAULT 0,
	"cd-jurisdicao-ent" varchar(40),
	"cod-estab-ctr" varchar(10),
	"nr-contrato" integer DEFAULT 0,
	"nr-seq-contr-it" integer DEFAULT 0,
	"ind-drop-shipment" bit DEFAULT 0,
	"nr-anexo" varchar(24) NOT NULL,
	"cod-class-fis" varchar(16),
	"cod-un" varchar(4),
	"cod-cta-contab" varchar(34),
	"cod-cust-contab" varchar(24),
	"log-desc-item-cli" bit DEFAULT 1,
	"log-canc-saldo" bit DEFAULT 1,
	"val-aliq-iss" numeric(17,2) DEFAULT 0,
	"qtd-alocar" numeric(17,2) DEFAULT 0,
	"val-ipi" numeric(19,4) DEFAULT 0,
	"ind-orig-entrada" integer DEFAULT 1,
	"log-preco-unid-medid-estoq" bit DEFAULT 1 NOT NULL,
	"val-frete" numeric(17,2) DEFAULT 0,
	"val-seguro" numeric(17,2) DEFAULT 0,
	"val-embal" numeric(17,2) DEFAULT 0,
	"cod-unid-negoc" varchar(6) NOT NULL,
	"val-tax-ptlidad" numeric(17,2) DEFAULT 0,
	"val-tax-apldo" numeric(17,2) DEFAULT 0,
	"qti-dias-carenc" integer DEFAULT 0,
	"cod-familia-mater" varchar(16),
	"val-preco-suger" numeric(25,10) DEFAULT 0,
	"sc-codigo" varchar(40),
	"ct-codigo" varchar(40),
	"num-id-campanha-crm" integer DEFAULT 0 NOT NULL,
	"cod-ord-compra" varchar(30),
	CONSTRAINT "ch-item-ped" PRIMARY KEY ("nome-abrev","nr-pedcli","nr-sequencia","it-codigo","cod-refer")
);
CREATE INDEX "ch-cli-ped" ON PUB."ped-item" ("nome-abrev","nr-pedcli","it-codigo","cod-refer","cod-entrega");
CREATE INDEX "ch-componen" ON PUB."ped-item" ("nome-abrev","nr-pedcli","ind-componen","cod-sit-item");
CREATE INDEX "ch-config" ON PUB."ped-item" ("nr-config");
CREATE INDEX "ch-contrato-venda" ON PUB."ped-item" ("nr-contrato","nr-anexo","nr-seq-contr-it","nome-abrev","nr-pedcli","nr-sequencia");
CREATE INDEX "ch-correcao" ON PUB."ped-item" ("it-codigo","cod-refer","cod-sit-item","nr-tabpre","tp-preco");
CREATE INDEX contrato ON PUB."ped-item" ("it-codigo","esp-ped");
CREATE INDEX "peditem-08" ON PUB."ped-item" ("nr-tabpre","cod-sit-item");
CREATE INDEX "peditem-09" ON PUB."ped-item" ("dt-entrega","cod-sit-item");
CREATE INDEX "peditem-10" ON PUB."ped-item" ("cod-ord-compra");
CREATE INDEX planejamento ON PUB."ped-item" ("it-codigo","cod-sit-item","dt-entrega");


-- PUB."ped-repre" definição

-- Drop table

-- DROP TABLE PUB."ped-repre";

CREATE TABLE PUB."ped-repre" (
	"nr-pedido" integer DEFAULT 0 NOT NULL,
	"nome-ab-rep" varchar(24) NOT NULL,
	"ind-repbase" bit DEFAULT 0 NOT NULL,
	"perc-comis" numeric(23,8) DEFAULT 0 NOT NULL,
	"comis-emis" integer DEFAULT 0 NOT NULL,
	"char-1" varchar(200),
	"char-2" varchar(200),
	"dec-1" numeric(23,8) DEFAULT 0,
	"dec-2" numeric(23,8) DEFAULT 0,
	"int-1" integer DEFAULT 0,
	"int-2" integer DEFAULT 0,
	"log-1" bit DEFAULT 0,
	"log-2" bit DEFAULT 0,
	"data-1" date DEFAULT NULL,
	"data-2" date DEFAULT NULL,
	"check-sum" varchar(40),
	"cod-classificador" varchar(16) NOT NULL,
	"idi-tip-comis-agent" integer DEFAULT 1 NOT NULL,
	"idi-tip-base-comis-agent" integer DEFAULT 1 NOT NULL,
	"idi-liber-pagto-comis-agent" integer DEFAULT 1 NOT NULL,
	"val-base-comis" numeric(17,2) DEFAULT 0,
	"val-comis" numeric(25,10) DEFAULT 0,
	"val-comis-emis" numeric(25,10) DEFAULT 0,
	CONSTRAINT "ch-pedrep1" PRIMARY KEY ("nr-pedido","nome-ab-rep","cod-classificador")
);
CREATE UNIQUE INDEX "ch-repped1" ON PUB."ped-repre" ("nome-ab-rep","nr-pedido","cod-classificador");


-- PUB."ped-venda" definição

-- Drop table

-- DROP TABLE PUB."ped-venda";

CREATE TABLE PUB."ped-venda" (
	"cod-estabel" varchar(10) NOT NULL,
	"nome-abrev" varchar(24) NOT NULL,
	"nr-pedcli" varchar(24) NOT NULL,
	"nr-pedido" integer DEFAULT 0 NOT NULL,
	"nr-pedrep" varchar(24),
	"dt-emissao" date DEFAULT sysdate NOT NULL,
	"dt-implant" date DEFAULT sysdate NOT NULL,
	"dt-entrega" date DEFAULT sysdate NOT NULL,
	"dt-cancela" date DEFAULT NULL,
	"desc-cancela" varchar(4000) NOT NULL,
	"dt-minfat" date DEFAULT NULL,
	"dt-lim-fat" date DEFAULT NULL,
	"dt-entorig" date DEFAULT sysdate,
	"dt-reativ" date DEFAULT NULL,
	"dt-devolucao" date DEFAULT NULL,
	"dt-suspensao" date DEFAULT NULL,
	"nat-operacao" varchar(12),
	"cod-cond-pag" integer DEFAULT 0,
	"nr-tabpre" varchar(16) NOT NULL,
	"nr-tab-finan" integer DEFAULT 0,
	"tp-pedido" varchar(4),
	"cod-priori" integer DEFAULT 0,
	"cod-entrega" varchar(24) NOT NULL,
	"local-entreg" varchar(80),
	bairro varchar(60),
	cidade varchar(50),
	estado varchar(8),
	cep varchar(24),
	"caixa-postal" varchar(20),
	pais varchar(40) DEFAULT Brasil,
	cgc varchar(38),
	"ins-estadual" varchar(38),
	"cod-sit-ped" integer DEFAULT 1,
	"perc-desco1" numeric(21,6) DEFAULT 0,
	"perc-desco2" numeric(21,6) DEFAULT 0,
	"cond-redespa" varchar(4000) NOT NULL,
	"cidade-cif" varchar(50),
	"cod-portador" integer DEFAULT 0,
	modalidade integer DEFAULT 0,
	"cod-mensagem" integer DEFAULT 0,
	observacoes varchar(4000),
	"cond-espec" varchar(4000) NOT NULL,
	"user-impl" varchar(24),
	"dt-userimp" date DEFAULT NULL,
	"user-alte" varchar(24),
	"dt-useralt" date DEFAULT NULL,
	"user-canc" varchar(24),
	"dt-usercan" date DEFAULT NULL,
	"user-reat" varchar(24),
	"dt-userrea" date DEFAULT NULL,
	"user-suspen" varchar(24),
	"dt-usersusp" date DEFAULT NULL,
	"ind-aprov" bit DEFAULT 0 NOT NULL,
	"quem-aprovou" varchar(24),
	"dt-apr-cred" date DEFAULT NULL,
	"cod-des-merc" integer DEFAULT 1,
	"nome-transp" varchar(24),
	"tp-preco" integer DEFAULT 1 NOT NULL,
	"ind-fat-par" bit DEFAULT 1 NOT NULL,
	"mo-codigo" integer DEFAULT 0 NOT NULL,
	"cod-rota" varchar(24) NOT NULL,
	"ind-lib-nota" bit DEFAULT 0 NOT NULL,
	"vl-tot-ped" numeric(25,10) DEFAULT 0 NOT NULL,
	"vl-liq-ped" numeric(25,10) DEFAULT 0,
	"vl-liq-abe" numeric(25,10) DEFAULT 0 NOT NULL,
	"ind-imp-ped" integer DEFAULT 1,
	"per-max-canc" numeric(17,2) DEFAULT 0 NOT NULL,
	"nr-ind-finan" integer DEFAULT 0 NOT NULL,
	"user-aprov" varchar(24),
	"no-ab-reppri" varchar(24) NOT NULL,
	"ind-antecip" bit DEFAULT 0,
	distancia numeric(16,1) DEFAULT 0 NOT NULL,
	"taxa-orig" numeric(20,5) DEFAULT 0 NOT NULL,
	"taxa-real" numeric(20,5) DEFAULT 0 NOT NULL,
	"vl-mer-abe" numeric(25,10) DEFAULT 0 NOT NULL,
	"cod-sit-aval" integer DEFAULT 1 NOT NULL,
	"desc-suspend" varchar(4000) NOT NULL,
	"desc-bloq-cr" varchar(1000) NOT NULL,
	"desc-forc-cr" varchar(152) NOT NULL,
	"nome-tr-red" varchar(24),
	"tip-cob-desp" integer DEFAULT 1 NOT NULL,
	"desc-txt" varchar(100),
	"cod-emitente" integer DEFAULT 0 NOT NULL,
	"cod-sit-pre" integer DEFAULT 1,
	"per-des-icms" numeric(18,3) DEFAULT 0 NOT NULL,
	"vl-cred-lib" numeric(17,2) DEFAULT 0,
	"inc-desc-txt" bit DEFAULT 1 NOT NULL,
	"dt-base-ft" date DEFAULT NULL,
	"aprov-forcado" varchar(24),
	"tp-receita" integer DEFAULT 0,
	"estab-atend" varchar(10) NOT NULL,
	"estab-central" varchar(10) NOT NULL,
	"esp-ped" integer DEFAULT 1 NOT NULL,
	"cd-origem" integer DEFAULT 1 NOT NULL,
	"proc-edi" integer DEFAULT NULL,
	"dt-inivig" date DEFAULT NULL,
	"dt-fimvig" date DEFAULT NULL,
	"dt-prev-vend" date DEFAULT NULL,
	"dsp-pre-fat" bit DEFAULT 1 NOT NULL,
	"cod-gr-cli" integer DEFAULT 0 NOT NULL,
	"nr-proforma" varchar(24),
	"tp-faturam" integer DEFAULT 1,
	contato varchar(50) NOT NULL,
	"nr-versao" varchar(24),
	origem integer DEFAULT 1,
	"cons-mrp" bit DEFAULT 1,
	"cons-pmp" bit DEFAULT 1,
	"invoice-id" varchar(2),
	"nr-proc-exp" varchar(24),
	atendido bit DEFAULT 0,
	permissao varchar(144) DEFAULT '*' NOT NULL,
	"zip-code" varchar(24),
	"replica-pd" bit DEFAULT 0,
	"nome-prog" varchar(40),
	"dt-mensagem" date DEFAULT sysdate,
	"cod-message-alerta" integer DEFAULT 0,
	"ind-ent-completa" bit DEFAULT 0,
	completo bit DEFAULT 0,
	"cod-tax" integer DEFAULT 0,
	"ind-orig-entrada" integer DEFAULT 1,
	"nro-proc-entrada" integer DEFAULT 0,
	"nro-proc-alteracao" integer DEFAULT 0,
	"ind-via-envio" integer DEFAULT 1,
	"nro-proc-saida" integer DEFAULT 0,
	"desc-reativa" varchar(4000),
	"e-mail" varchar(80),
	"char-1" varchar(200),
	"char-2" varchar(200),
	"dec-1" numeric(23,8) DEFAULT 0,
	"dec-2" numeric(23,8) DEFAULT 0,
	"int-1" integer DEFAULT 0,
	"int-2" integer DEFAULT 0,
	"log-1" bit DEFAULT 0,
	"log-2" bit DEFAULT 0,
	"data-1" date DEFAULT NULL,
	"data-2" date DEFAULT NULL,
	"cod-canal-venda" integer DEFAULT 0,
	"vl-desconto" numeric(25,10) DEFAULT 0,
	"cod-imagem" varchar(60),
	"nr-cotacao" integer DEFAULT 0,
	"dt-entrega-prim" date DEFAULT sysdate,
	"cd-cancela" integer DEFAULT 0,
	"tab-ind-fin" numeric(20,5) DEFAULT 1,
	"cod-sit-com" integer DEFAULT 1,
	"motivo-alt-sit-quota" varchar(4000),
	"dat-alter-sit" date DEFAULT sysdate,
	"cod-usu-alt-sit" varchar(24),
	"check-sum" varchar(40),
	"log-usa-tabela-desconto" bit DEFAULT 1 NOT NULL,
	"val-pct-desconto-tab-preco" numeric(25,10) DEFAULT 0 NOT NULL,
	"des-pct-desconto-inform" varchar(100),
	"val-pct-desconto-valor" numeric(25,10) DEFAULT 0 NOT NULL,
	"val-pct-desconto-total" numeric(25,10) DEFAULT 0 NOT NULL,
	"log-ped-bonif-pendente" bit DEFAULT 0,
	"log-pedido-alterado" bit DEFAULT 0,
	"ind-sit-desconto" integer DEFAULT 1 NOT NULL,
	"dat-sit-desconto" date DEFAULT NULL,
	"cod-usu-lib-desconto" varchar(24),
	"desc-lib-desconto" varchar(152) NOT NULL,
	"val-desconto-total" numeric(25,10) DEFAULT 0,
	"estab-destino" varchar(10) NOT NULL,
	"cod-sit-preco" integer DEFAULT 1 NOT NULL,
	"user-preco" varchar(24),
	"dat-aprov-preco" date DEFAULT sysdate,
	"desc-lib-preco" varchar(152) NOT NULL,
	placa varchar(20),
	"uf-placa" varchar(4),
	"mo-fatur" integer DEFAULT 0 NOT NULL,
	"nr-invoice" varchar(32) NOT NULL,
	"num-pedido-origem" varchar(24),
	"ind-tp-frete" integer DEFAULT 1,
	"nr-ped-cot-orig" varchar(24),
	"log-cotacao" bit DEFAULT 0 NOT NULL,
	"cod-mot-canc-cot" integer DEFAULT 0,
	"user-aprov-cot" varchar(24),
	"dt-aprov-cot" date DEFAULT NULL,
	"dt-validade-cot" date DEFAULT NULL,
	"nome-abrev-tri" varchar(24),
	"cod-entrega-tri" varchar(24),
	"num-pedido-bonif" varchar(24),
	"pct-min-rentab" numeric(17,2) DEFAULT 0,
	"log-cot-impressa" bit DEFAULT 0,
	"log-pedido-mp" bit DEFAULT 0,
	endereco_text varchar(4000),
	"cd-jurisdicao-ent" varchar(40),
	"ind-ender-fatur" bit DEFAULT 1,
	"nr-contrato" integer DEFAULT 0,
	"nr-anexo" varchar(24) NOT NULL,
	"desc-valor-ped" numeric(20,5) DEFAULT 0,
	"pedido-mp" bit DEFAULT 0,
	"log-atual-cotas" bit DEFAULT 0,
	"cod-rma" varchar(32),
	"nr-pedido-crm" integer DEFAULT 0,
	"log-juros-prorate" bit DEFAULT 0 NOT NULL,
	"cdn-motiv-reprovac-cr" integer DEFAULT 0,
	"cod-ped-clien-mp" varchar(24) NOT NULL,
	"val-perc-frete" numeric(17,2) DEFAULT 0,
	"val-perc-seguro" numeric(17,2) DEFAULT 0,
	"val-perc-embal" numeric(17,2) DEFAULT 0,
	"val-frete" numeric(17,2) DEFAULT 0,
	"val-seguro" numeric(17,2) DEFAULT 0,
	"val-embal" numeric(17,2) DEFAULT 0,
	"cod-unid-negoc" varchar(6),
	"num-dias-praz-med-cond-esp" integer DEFAULT 0,
	"hra-emis-ped" varchar(16),
	"hra-atualiz" varchar(16) DEFAULT '000000',
	"val-pct-desc-politic-bonifi" numeric(17,2) DEFAULT 0,
	"cod-safra" varchar(18) DEFAULT '00000000',
	"dat-base-preco" date DEFAULT sysdate,
	"num-id-oportun-vda" integer DEFAULT 0 NOT NULL,
	"num-id-campanha-crm" integer DEFAULT 0 NOT NULL,
	"cod-id-prosp" varchar(24) NOT NULL,
	"cod-workflow" varchar(200) NOT NULL,
	"log-aprov-workflow" bit DEFAULT 0 NOT NULL,
	CONSTRAINT "ch-pedseq" PRIMARY KEY ("nr-pedido")
);
CREATE INDEX "ch-avalia" ON PUB."ped-venda" ("cod-sit-aval","nome-abrev");
CREATE INDEX "ch-canal" ON PUB."ped-venda" ("dsp-pre-fat","cod-canal-venda","dt-entrega","nome-abrev","nr-pedcli");
CREATE INDEX "ch-cli-ped-ent" ON PUB."ped-venda" ("dsp-pre-fat","nome-abrev","nr-pedcli","dt-entrega");
CREATE INDEX "ch-condpag" ON PUB."ped-venda" ("cod-cond-pag");
CREATE INDEX "ch-contrato-venda" ON PUB."ped-venda" ("nr-contrato","nr-anexo","nome-abrev","nr-pedcli");
CREATE INDEX "ch-credito" ON PUB."ped-venda" ("nome-abrev","cod-sit-ped","cod-sit-aval");
CREATE INDEX "ch-ent-pr-cli" ON PUB."ped-venda" ("dsp-pre-fat","dt-entrega","cod-priori","nome-abrev");
CREATE INDEX "ch-estcli" ON PUB."ped-venda" ("cod-estabel","nome-abrev");
CREATE INDEX "ch-implant" ON PUB."ped-venda" ("dt-implant","cod-sit-ped");
CREATE INDEX "ch-natoper" ON PUB."ped-venda" ("nat-operacao");
CREATE INDEX "ch-nr-pedcli" ON PUB."ped-venda" ("nr-pedcli","nome-abrev");
CREATE INDEX "ch-ped-origem" ON PUB."ped-venda" ("nome-abrev","num-pedido-origem");
CREATE UNIQUE INDEX "ch-pedido" ON PUB."ped-venda" ("nome-abrev","nr-pedcli");
CREATE INDEX "ch-portador" ON PUB."ped-venda" ("cod-portador",modalidade);
CREATE INDEX "ch-pr-ent-cli" ON PUB."ped-venda" ("dsp-pre-fat","cod-priori","dt-entrega","nome-abrev");
CREATE INDEX "ch-pre-fat" ON PUB."ped-venda" ("dt-entrega","cod-priori","cod-sit-ped","cod-estabel","nome-abrev","nr-pedcli");
CREATE INDEX "ch-rep-cli" ON PUB."ped-venda" ("no-ab-reppri","nome-abrev","cod-sit-ped");
CREATE INDEX "ch-rep-cli-ent" ON PUB."ped-venda" ("dsp-pre-fat","no-ab-reppri","nome-abrev","dt-entrega");
CREATE INDEX "ch-rota" ON PUB."ped-venda" ("cod-rota","nome-abrev","nr-pedcli");
CREATE INDEX "ch-situ-pre" ON PUB."ped-venda" ("cod-sit-preco","cod-sit-ped","log-cotacao");
CREATE INDEX "ch-tabfin" ON PUB."ped-venda" ("cod-sit-ped","nr-tab-finan");
CREATE INDEX "ch-tabpre" ON PUB."ped-venda" ("nr-tabpre","cod-sit-ped","tp-preco");
CREATE INDEX "ch-transp" ON PUB."ped-venda" ("nome-transp");
CREATE INDEX "estab-sit-com" ON PUB."ped-venda" ("cod-estabel","cod-sit-com","dt-entrega");
CREATE INDEX "pedvda-28" ON PUB."ped-venda" ("log-cotacao","nome-abrev","nr-pedcli");
CREATE INDEX "pedvda-29" ON PUB."ped-venda" ("nome-tr-red");
CREATE INDEX "pedvda-30" ON PUB."ped-venda" ("log-cotacao","cod-sit-com","nome-abrev","nr-pedcli");
CREATE INDEX "pedvda-31" ON PUB."ped-venda" ("dt-useralt","hra-atualiz");
CREATE INDEX "pedvda-32" ON PUB."ped-venda" ("log-cotacao","dt-implant","nome-abrev");
CREATE INDEX "pedvda-cotac" ON PUB."ped-venda" ("log-cotacao","nr-ped-cot-orig");

-- PUB.item definição

-- Drop table

-- DROP TABLE PUB.item;

CREATE TABLE PUB.item (
	"it-codigo" varchar(32) NOT NULL,
	"descricao-1" varchar(36) NOT NULL,
	"descricao-2" varchar(36) NOT NULL,
	un varchar(4) NOT NULL,
	"compr-fabric" integer DEFAULT 1 NOT NULL,
	"ge-codigo" integer DEFAULT 0 NOT NULL,
	"fm-codigo" varchar(16) NOT NULL,
	"data-implant" date DEFAULT sysdate NOT NULL,
	"data-liberac" date DEFAULT sysdate NOT NULL,
	"path" varchar(80),
	"codigo-refer" varchar(40) NOT NULL,
	"inform-compl" varchar(32) NOT NULL,
	"niv-mais-bai" integer DEFAULT 0 NOT NULL,
	"loc-unica" bit DEFAULT 1 NOT NULL,
	"tipo-con-est" integer DEFAULT 1 NOT NULL,
	"deposito-pad" varchar(6) NOT NULL,
	"ciclo-contag" integer DEFAULT 0 NOT NULL,
	"data-ult-con" date DEFAULT '01/01/1800',
	"variac-acum" numeric(19,4) DEFAULT 0 NOT NULL,
	"curva-abc" bit DEFAULT 0 NOT NULL,
	"data-ult-ent" date DEFAULT NULL,
	"data-ult-sai" date DEFAULT NULL,
	"data-base" date DEFAULT NULL,
	"data-ult-rep" date DEFAULT NULL,
	"cod-obsoleto" integer DEFAULT 1 NOT NULL,
	"consumo-prev" numeric(19,4) DEFAULT 0 NOT NULL,
	"consumo-aad" numeric(19,4) DEFAULT 0 NOT NULL,
	"cod-comprado" varchar(24) NOT NULL,
	demanda integer DEFAULT 1 NOT NULL,
	"emissao-ord" integer DEFAULT 1 NOT NULL,
	"classif-abc" integer DEFAULT 3 NOT NULL,
	politica integer DEFAULT 1 NOT NULL,
	"periodo-fixo" integer DEFAULT 1 NOT NULL,
	"tempo-segur" integer DEFAULT 7 NOT NULL,
	"quant-segur" numeric(19,4) DEFAULT 0 NOT NULL,
	"res-int-comp" integer DEFAULT 0 NOT NULL,
	"res-for-comp" integer DEFAULT 0 NOT NULL,
	"res-cq-comp" integer DEFAULT 0 NOT NULL,
	"ressup-fabri" integer DEFAULT 0 NOT NULL,
	"res-cq-fabri" integer DEFAULT 0 NOT NULL,
	"lote-multipl" numeric(19,4) DEFAULT 1 NOT NULL,
	"tipo-lote-ec" integer DEFAULT 1 NOT NULL,
	"lote-economi" numeric(19,4) DEFAULT 1 NOT NULL,
	"fator-refugo" numeric(17,2) DEFAULT 0 NOT NULL,
	"quant-perda" numeric(19,4) DEFAULT 0 NOT NULL,
	"classe-repro" integer DEFAULT 1 NOT NULL,
	"contr-qualid" bit DEFAULT 0 NOT NULL,
	"class-fiscal" varchar(20) NOT NULL,
	"aliquota-ipi" numeric(17,2) DEFAULT 0 NOT NULL,
	"codigo-orig" integer DEFAULT 1 NOT NULL,
	"cd-trib-icm" integer DEFAULT 1 NOT NULL,
	"cd-trib-ipi" integer DEFAULT 1 NOT NULL,
	"peso-liquido" numeric(20,5) DEFAULT 0 NOT NULL,
	"fator-conver" numeric(20,5) DEFAULT 1 NOT NULL,
	"tipo-desc-nt" integer DEFAULT 1 NOT NULL,
	"baixa-estoq" bit DEFAULT 1 NOT NULL,
	"moeda-padrao" integer DEFAULT 0 NOT NULL,
	"preco-base" numeric(19,4) DEFAULT 0 NOT NULL,
	"preco-ul-ent" numeric(19,4) DEFAULT 0 NOT NULL,
	"preco-repos" numeric(19,4) DEFAULT 0 NOT NULL,
	"cd-planejado" varchar(24) NOT NULL,
	"nr-linha" integer DEFAULT 0 NOT NULL,
	"tipo-requis" integer DEFAULT 1 NOT NULL,
	"cap-est-fabr" numeric(19,4) DEFAULT 0 NOT NULL,
	"tipo-contr" integer DEFAULT 2 NOT NULL,
	"tipo-est-seg" integer DEFAULT 1,
	"dt-ult-ben" date DEFAULT NULL,
	"ft-conversao" numeric(15,0) DEFAULT 0 NOT NULL,
	"dec-ftcon" integer DEFAULT 0 NOT NULL,
	"pm-ja-calc" bit DEFAULT 0 NOT NULL,
	fraciona bit DEFAULT 1 NOT NULL,
	"reporte-mob" integer DEFAULT 1 NOT NULL,
	"ind-item-fat" bit DEFAULT 1 NOT NULL,
	"peso-bruto" numeric(20,5) DEFAULT 0 NOT NULL,
	"cd-trib-iss" integer DEFAULT 1 NOT NULL,
	"aliquota-ISS" numeric(17,2) DEFAULT 0 NOT NULL,
	"ind-imp-desc" integer DEFAULT 1 NOT NULL,
	"ind-ipi-dife" bit DEFAULT 0 NOT NULL,
	"lote-minimo" numeric(19,4) DEFAULT 1 NOT NULL,
	"ind-inf-qtf" bit DEFAULT 0,
	"vl-mat-ant" numeric(19,4) DEFAULT 0 NOT NULL,
	"vl-mob-ant" numeric(19,4) DEFAULT 0 NOT NULL,
	responsavel varchar(24) NOT NULL,
	"usuario-alt" varchar(24) DEFAULT NULL,
	"data-obsol" date DEFAULT NULL,
	"usuario-obsol" varchar(24),
	criticidade integer DEFAULT 1 NOT NULL,
	"horiz-fixo" integer DEFAULT 0 NOT NULL,
	"lote-mulven" numeric(19,4) DEFAULT 1 NOT NULL,
	"cod-servico" integer DEFAULT 0 NOT NULL,
	comprim numeric(23,8) DEFAULT 0 NOT NULL,
	largura numeric(23,8) DEFAULT 0 NOT NULL,
	altura numeric(23,8) DEFAULT 0 NOT NULL,
	"qt-max-ordem" numeric(19,4) DEFAULT NULL,
	"perm-saldo-neg" integer DEFAULT 1 NOT NULL,
	"dt-pr-fisc" date DEFAULT NULL,
	"preco-fiscal" numeric(19,4) DEFAULT 0 NOT NULL,
	"ct-codigo" varchar(40) NOT NULL,
	"sc-codigo" varchar(40) NOT NULL,
	"pr-sem-tx" numeric(19,4) DEFAULT 0 NOT NULL,
	"div-ordem" integer DEFAULT 1 NOT NULL,
	"cod-estabel" varchar(10) NOT NULL,
	"cod-produto" varchar(32) NOT NULL,
	"fm-cod-com" varchar(16),
	"ft-conv-fmcoml" numeric(15,0) DEFAULT 0 NOT NULL,
	volume numeric(20,5) DEFAULT 0 NOT NULL,
	"desc-nacional" varchar(72),
	"desc-inter" varchar(72),
	"ind-especifico" bit DEFAULT 0,
	"per-min-luc" numeric(17,2) DEFAULT 0,
	"ind-backorder" bit DEFAULT 0,
	"rep-prod" integer DEFAULT 1 NOT NULL,
	"cd-formula" integer DEFAULT 1,
	"cd-origem" integer DEFAULT 1,
	"tp-cons-prev" numeric(15,0) DEFAULT 0,
	"tp-aloc-lote" integer DEFAULT 1,
	"tp-desp-padrao" integer DEFAULT 0,
	"id-grade" bit DEFAULT 0,
	"nat-despesa" integer DEFAULT 0,
	"tp-adm-lote" integer DEFAULT 1,
	"per-rest-icms" numeric(17,2) DEFAULT 0 NOT NULL,
	"niv-rest-icms" varchar(2),
	concentracao numeric(19,4) DEFAULT 0 NOT NULL,
	rendimento numeric(19,4) DEFAULT 0 NOT NULL,
	nivel integer DEFAULT 0 NOT NULL,
	"tipo-insp" integer DEFAULT 1 NOT NULL,
	"perc-nqa" numeric(18,3) DEFAULT 0,
	"per-rest-fora" numeric(17,2) DEFAULT 0,
	"niv-rest-fora" varchar(2),
	"nr-item-dcr" integer DEFAULT 0,
	"tx-importacao" numeric(18,3) DEFAULT 0,
	prioridade integer DEFAULT 0 NOT NULL,
	"tipo-sched" integer DEFAULT 1 NOT NULL,
	"atu-conf" bit DEFAULT 1,
	"isencao-import" integer DEFAULT 1,
	"resumo-mp" integer DEFAULT 1 NOT NULL,
	"ind-serv-mat" integer DEFAULT 2,
	"cod-refer" varchar(16),
	"niv-mps" integer DEFAULT 0,
	"calc-cons-prev" integer DEFAULT 1 NOT NULL,
	"var-transf" numeric(17,2) DEFAULT 0 NOT NULL,
	"var-rep" numeric(17,2) DEFAULT 0 NOT NULL,
	"var-req-maior" numeric(17,2) DEFAULT 0,
	"var-req-menor" numeric(17,2) DEFAULT 0,
	"de-codigo-prin" varchar(32) NOT NULL,
	"contr-plan" integer DEFAULT 1 NOT NULL,
	"calc-lead-time" integer DEFAULT 1,
	"dec-conv-fmcoml" integer DEFAULT 0 NOT NULL,
	"fase-medio" integer DEFAULT 1,
	"cod-auxiliar" varchar(80),
	"var-mob-maior" numeric(17,2) DEFAULT 0,
	"var-mob-menor" numeric(17,2) DEFAULT 0,
	"it-demanda" varchar(32),
	"perc-demanda" numeric(17,2) DEFAULT 100,
	"cd-folh-lote" varchar(16),
	"cd-folh-item" varchar(16),
	"valor-ipi-beb" numeric(20,5) DEFAULT 0,
	"esp-beb" integer DEFAULT 0,
	"enquad-beb" integer DEFAULT 0,
	"tipo-recip-beb" integer DEFAULT 1,
	"capac-recip-beb" integer DEFAULT 1,
	"rot-quant" bit DEFAULT 0,
	"rot-revis" bit DEFAULT 0,
	"rot-refer" bit DEFAULT 0,
	"alt-refer" bit DEFAULT 1,
	"tipo-atp" integer DEFAULT 1,
	"fator-reaj-icms" numeric(23,8) DEFAULT 0,
	incentivado bit DEFAULT 0,
	"prefixo-lote" varchar(10),
	"Nr-ult-peca" integer DEFAULT 0,
	"tp-lote-minimo" bit DEFAULT 1,
	"tp-lote-multiplo" bit DEFAULT 1,
	"tp-lote-econom" bit DEFAULT 1,
	"quant-pacote" numeric(19,4) DEFAULT 0,
	"conta-aplicacao" varchar(34),
	"cod-localiz" varchar(20),
	"sit-aloc" integer DEFAULT 1,
	"cd-tag" varchar(32),
	"cod-tax" integer DEFAULT 0,
	"cod-tax-serv" integer DEFAULT 0,
	"desc-item" varchar(120),
	narrativa varchar(4000),
	"log-carac-tec" bit DEFAULT 1 NOT NULL,
	"cod-lista-destino" varchar(16),
	"log-atualiz-via-mmp" bit DEFAULT 0,
	"vl-var-max" numeric(17,2) DEFAULT 0,
	"vl-var-min" numeric(17,2) DEFAULT 0,
	"qt-var-max" numeric(17,2) DEFAULT 0,
	"qt-var-min" numeric(17,2) DEFAULT 0,
	"reporte-ggf" integer DEFAULT 1 NOT NULL,
	"cod-imagem" varchar(60),
	"cd-referencia" varchar(8),
	"conv-tempo-seg" bit DEFAULT 0,
	"char-1" varchar(400),
	"char-2" varchar(400),
	"dec-1" numeric(23,8) DEFAULT 0,
	"dec-2" numeric(23,8) DEFAULT 0,
	"INT-1" integer DEFAULT 0,
	"int-2" integer DEFAULT 0,
	"log-1" bit DEFAULT 0,
	"log-2" bit DEFAULT 0,
	"data-1" date DEFAULT NULL,
	"data-2" date DEFAULT NULL,
	"ind-confprodcom" bit DEFAULT 0,
	"nivel-apr-requis" integer DEFAULT 0,
	"nivel-apr-solic" integer DEFAULT 0,
	"nivel-apr-manut" integer DEFAULT 0,
	"nivel-apr-compra" integer DEFAULT 0,
	"ind-prev-demanda" integer DEFAULT 1 NOT NULL,
	"ind-calc-meta" integer DEFAULT 1 NOT NULL,
	"val-fator-custo-dis" numeric(17,2) DEFAULT 0 NOT NULL,
	"qtd-refer-custo-dis" numeric(17,2) DEFAULT 1,
	"qtd-batch-padrao" numeric(19,4) DEFAULT 1 NOT NULL,
	"log-utiliza-batch-padrao" bit DEFAULT 0 NOT NULL,
	"ind-quotas" bit DEFAULT 0,
	"nr-pontos-quotas" integer DEFAULT 0,
	"check-sum" varchar(40),
	"num-id-item" integer DEFAULT 0 NOT NULL,
	"ind-refugo" integer DEFAULT 1 NOT NULL,
	"log-necessita-li" bit DEFAULT 1,
	"dias-estoq-aloc" varchar(16),
	"pto-repos" numeric(19,4) DEFAULT 0,
	"aliquota-ii" numeric(17,2) DEFAULT 0,
	"cod-trib-ii" integer DEFAULT 1,
	"geracao-ordem" integer DEFAULT 0,
	"cons-produto" bit DEFAULT 0,
	"cons-saldo" bit DEFAULT 1,
	"mp-restrit" bit DEFAULT 0,
	"qtde-max" numeric(19,4) DEFAULT 0,
	"qtde-fixa" numeric(19,4) DEFAULT 0,
	"lote-repos" numeric(17,2) DEFAULT 0,
	"cons-consumo" bit DEFAULT 0,
	"cod-malha" varchar(10) DEFAULT '0',
	"cod-pulmao" varchar(10),
	"politica-aps" integer DEFAULT 0,
	"tipo-formula" integer DEFAULT 1 NOT NULL,
	"per-ppm" numeric(19,4) DEFAULT 0,
	"cod-tab-preco-aps" varchar(16),
	"cod-pulmao-proces" varchar(16) NOT NULL,
	"log-tax-produc" bit DEFAULT 0 NOT NULL,
	"log-control-estoq-refugo" bit DEFAULT 0,
	"log-refugo-preco-fisc" bit DEFAULT 0,
	"cod-item-refugo" varchar(32),
	"val-relac-refugo-item" numeric(20,5) DEFAULT 0,
	"log-multi-malha" bit DEFAULT 0,
	"cod-destaq" integer DEFAULT 0 NOT NULL,
	"dsl-destaq" varchar(4000) NOT NULL,
	"idi-classif-item" integer DEFAULT 1,
	"cod-unid-negoc" varchar(6),
	"log-consid-aloc-ativid" bit DEFAULT 1 NOT NULL,
	"val-overlap" numeric(17,2) DEFAULT 0,
	"log-programac-sfc" bit DEFAULT 1,
	"cod-dcr-item" varchar(24),
	"log-orig-ext" bit DEFAULT 0,
	"log-altera-valid-lote" bit DEFAULT 0,
	"log-inspec-lote" bit DEFAULT 0,
	"cod-workflow" varchar(200),
	"log-benef" bit DEFAULT 0,
	"cdn-emit-benef" integer DEFAULT 0,
	"log-recalc-sdo-terc" bit DEFAULT 0,
	CONSTRAINT codigo PRIMARY KEY ("it-codigo")
);
CREATE INDEX "ch-auxiliar" ON PUB.item ("cod-auxiliar");
CREATE INDEX "ch-codser" ON PUB.item ("cod-servico");
CREATE INDEX "ch-fm-coml" ON PUB.item ("fm-cod-com","it-codigo");
CREATE INDEX "ch-localiz" ON PUB.item ("cod-estabel","deposito-pad","cod-localiz");
CREATE INDEX "ch-malha" ON PUB.item ("cod-malha");
CREATE INDEX "class-fiscal" ON PUB.item ("class-fiscal","it-codigo");
CREATE INDEX "cod-obsoleto" ON PUB.item ("cod-obsoleto");
CREATE INDEX complementar ON PUB.item ("codigo-refer");
CREATE INDEX "compr-fabric" ON PUB.item ("compr-fabric");
CREATE INDEX comprador ON PUB.item ("cod-comprado","it-codigo");
CREATE INDEX demanda ON PUB.item (demanda);
CREATE INDEX "desc-item-wi" ON PUB.item ("desc-item");
CREATE INDEX descricao ON PUB.item ("desc-item");
CREATE INDEX "fam-ge" ON PUB.item ("fm-codigo","ge-codigo","compr-fabric","contr-plan",demanda);
CREATE INDEX familia ON PUB.item ("fm-codigo","it-codigo");
CREATE INDEX "folh-item" ON PUB.item ("cd-folh-item");
CREATE INDEX grupo ON PUB.item ("ge-codigo","it-codigo");
CREATE INDEX "item-refugo" ON PUB.item ("cod-item-refugo");
CREATE INDEX "item-workflow" ON PUB.item ("cod-workflow");
CREATE INDEX linha ON PUB.item ("nr-linha","it-codigo");
CREATE INDEX "natur-item" ON PUB.item ("nat-despesa","it-codigo");
CREATE INDEX nmb ON PUB.item ("niv-mais-bai" DESC);
CREATE INDEX planejador ON PUB.item ("cd-planejado","it-codigo","tipo-contr","tipo-requis");
CREATE INDEX politica ON PUB.item (politica,"it-codigo");
CREATE INDEX token ON PUB.item ("num-id-item");
CREATE INDEX un ON PUB.item (un,"it-codigo");
CREATE INDEX "unid-neg" ON PUB.item ("cod-unid-negoc");