-- PUB.emitente definição

-- Drop table

-- DROP TABLE PUB.emitente;

CREATE TABLE PUB.emitente (
	"cod-emitente" integer DEFAULT 0 NOT NULL,
	"nome-abrev" varchar(24) NOT NULL,
	cgc varchar(38),
	identific integer DEFAULT 1 NOT NULL,
	natureza integer DEFAULT 1 NOT NULL,
	"nome-emit" varchar(160) NOT NULL,
	endereco varchar(80) NOT NULL,
	bairro varchar(60) NOT NULL,
	cidade varchar(50) NOT NULL,
	estado varchar(8) NOT NULL,
	cep varchar(24) NOT NULL,
	"caixa-postal" varchar(20),
	pais varchar(40) NOT NULL,
	"ins-estadual" varchar(38) NOT NULL,
	"cod-cond-pag" integer DEFAULT 0,
	"taxa-financ" numeric(17,2) DEFAULT 0 NOT NULL,
	"data-taxa" date DEFAULT sysdate,
	"cod-transp" integer DEFAULT 0 NOT NULL,
	"cod-gr-forn" integer DEFAULT 0,
	"linha-produt" varchar(16) NOT NULL,
	atividade varchar(24) NOT NULL,
	contato varchar(52) NOT NULL,
	telefone varchar(64) NOT NULL,
	ramal varchar(24) NOT NULL,
	telefax varchar(30) NOT NULL,
	"ramal-fax" varchar(10),
	telex varchar(30) NOT NULL,
	"data-implant" date DEFAULT sysdate NOT NULL,
	"compr-period" numeric(17,2) DEFAULT 0,
	"end-cobranca" integer DEFAULT 0 NOT NULL,
	"cod-rep" integer DEFAULT 0 NOT NULL,
	categoria varchar(6) NOT NULL,
	bonificacao numeric(18,3) DEFAULT 0 NOT NULL,
	istr integer DEFAULT 0 NOT NULL,
	"cod-gr-cli" integer DEFAULT 0 NOT NULL,
	"lim-credito" numeric(17,2) DEFAULT 0 NOT NULL,
	"dt-lim-cred" date DEFAULT NULL,
	"perc-fat-ped" integer DEFAULT 0 NOT NULL,
	portador integer DEFAULT 0 NOT NULL,
	modalidade integer DEFAULT 0 NOT NULL,
	"ind-fat-par" bit DEFAULT 1 NOT NULL,
	"ind-cre-cli" integer DEFAULT 1 NOT NULL,
	"ind-apr-cred" bit DEFAULT 0 NOT NULL,
	"nat-operacao" varchar(12) NOT NULL,
	observacoes varchar(4000) NOT NULL,
	"per-minfat" numeric(17,2) DEFAULT 0,
	"emissao-ped" integer DEFAULT 1,
	"nome-matriz" varchar(24) NOT NULL,
	"telef-modem" varchar(30),
	"ramal-modem" varchar(14),
	"telef-fac" varchar(30),
	"ramal-fac" varchar(10),
	agencia varchar(16) NOT NULL,
	"nr-titulo" integer DEFAULT 0,
	"nr-dias" integer DEFAULT 0,
	"per-max-canc" numeric(17,2) DEFAULT 0 NOT NULL,
	"dt-ult-venda" date DEFAULT NULL,
	"emite-bloq" bit DEFAULT 0,
	"emite-etiq" bit DEFAULT 0 NOT NULL,
	"tr-ar-valor" integer DEFAULT 1 NOT NULL,
	"gera-ad" bit DEFAULT 0 NOT NULL,
	"port-prefer" integer DEFAULT 0,
	"mod-prefer" integer DEFAULT 1 NOT NULL,
	"bx-acatada" integer DEFAULT 0 NOT NULL,
	"conta-corren" varchar(40) NOT NULL,
	"nr-copias-ped" integer DEFAULT 1 NOT NULL,
	"cod-suframa" varchar(40) NOT NULL,
	"cod-cacex" varchar(40) NOT NULL,
	"gera-difer" integer DEFAULT 0 NOT NULL,
	"nr-tabpre" varchar(16) NOT NULL,
	"ind-aval" integer DEFAULT 1 NOT NULL,
	"user-libcre" varchar(24) NOT NULL,
	"ins-banc" varchar(16) DEFAULT '0',
	"ven-feriado" integer DEFAULT 1 NOT NULL,
	"ven-domingo" integer DEFAULT 1 NOT NULL,
	"ven-sabado" integer DEFAULT 1 NOT NULL,
	"cgc-cob" varchar(38) NOT NULL,
	"cep-cob" varchar(24),
	"estado-cob" varchar(8) NOT NULL,
	"cidade-cob" varchar(50) NOT NULL,
	"bairro-cob" varchar(60) NOT NULL,
	"endereco-cob" varchar(80) NOT NULL,
	"cx-post-cob" varchar(20),
	"ins-est-cob" varchar(38) NOT NULL,
	"nome-mic-reg" varchar(24),
	"tip-cob-desp" integer DEFAULT 1,
	"nome-tr-red" varchar(24),
	"nat-ope-ext" varchar(12),
	"cod-banco" integer DEFAULT 0 NOT NULL,
	"prox-ad" integer DEFAULT 0 NOT NULL,
	"lim-adicional" numeric(17,2) DEFAULT 0,
	"dt-fim-cred" date DEFAULT NULL,
	"obs-entrega" varchar(4000),
	"cod-tip-ent" integer DEFAULT 0,
	"ins-municipal" varchar(38) NOT NULL,
	"nr-peratr" integer DEFAULT 0 NOT NULL,
	"nr-mesina" integer DEFAULT 0 NOT NULL,
	"insc-subs-trib" varchar(38),
	"cod-mensagem" integer DEFAULT 0 NOT NULL,
	"nr-dias-taxa" integer DEFAULT 0,
	"tp-desp-padrao" integer DEFAULT 0,
	"tp-rec-padrao" integer DEFAULT 0,
	"inf-complementar" varchar(24),
	"zip-code" varchar(24),
	"tp-inspecao" integer DEFAULT 2,
	"forn-exp" bit DEFAULT 0 NOT NULL,
	"tp-qt-prg" integer DEFAULT 1 NOT NULL,
	"ind-atraso" integer DEFAULT 1 NOT NULL,
	"ind-div-atraso" integer DEFAULT 1 NOT NULL,
	"ind-dif-atrs-1" integer DEFAULT 1 NOT NULL,
	"ind-dif-atrs-2" integer DEFAULT 1 NOT NULL,
	"esp-pd-venda" integer DEFAULT 0 NOT NULL,
	"ind-lib-estoque" bit DEFAULT 0,
	"ind-moeda-tit" integer DEFAULT 0,
	"ind-rendiment" bit DEFAULT 0,
	"tp-pagto" integer DEFAULT 1,
	"vl-min-ad" numeric(17,2) DEFAULT 0,
	"zip-cob-code" varchar(24),
	"hora-ini" integer DEFAULT 0,
	"hora-fim" integer DEFAULT 0,
	"pais-cob" varchar(40),
	"resumo-mp" integer DEFAULT 2 NOT NULL,
	"ind-cred-abat" bit DEFAULT 0,
	"contrib-icms" bit DEFAULT 1,
	"e-mail" varchar(80),
	"home-page" varchar(80),
	"ind-licenciador" bit DEFAULT 0,
	endereco2 varchar(80),
	"ind-aval-embarque" integer DEFAULT 1,
	"ind-abrange-aval" integer DEFAULT 1,
	"cod-tax" integer DEFAULT 0,
	"cn-codigo" varchar(40),
	"cod-entrega" varchar(24),
	"cod-isencao" integer DEFAULT 0,
	"dias-comp" integer DEFAULT 0,
	estoque integer DEFAULT 1,
	"flag-pag" integer DEFAULT 1,
	"item-cli" bit DEFAULT 0,
	"moeda-libcre" integer DEFAULT 0,
	"nr-dias-atraso" integer DEFAULT 0,
	"valor-minimo" numeric(17,2) DEFAULT 0,
	"cod-parceiro-edi" integer DEFAULT 0,
	"agente-retencao" bit DEFAULT 0,
	percepcao bit DEFAULT 0,
	"char-1" varchar(4000),
	"char-2" varchar(200),
	"dec-1" numeric(23,8) DEFAULT 0,
	"dec-2" numeric(23,8) DEFAULT 0,
	"int-1" integer DEFAULT 0,
	"int-2" integer DEFAULT 0,
	"log-1" bit DEFAULT 0,
	"log-2" bit DEFAULT 0,
	"data-1" date DEFAULT NULL,
	"data-2" date DEFAULT NULL,
	"cod-canal-venda" integer DEFAULT 0,
	"ind-sit-emitente" integer DEFAULT 1,
	"ind-emit-retencao" integer DEFAULT 2,
	"calcula-multa" bit DEFAULT 1 NOT NULL,
	"prog-emit" bit DEFAULT 0,
	"nr-tab-progr" integer DEFAULT 0,
	"recebe-inf-sci" bit DEFAULT 0,
	"cod-classif-fornec" integer DEFAULT 0,
	"cod-classif-cliente" integer DEFAULT 0,
	"nr-cheque-devol" integer DEFAULT 0,
	"periodo-devol" integer DEFAULT 0,
	"vl-max-devol" numeric(17,2) DEFAULT 0,
	"check-sum" varchar(40),
	"val-quota-media" numeric(19,4) DEFAULT 0,
	"cod-repres-imp" integer DEFAULT 0,
	"vencto-dia-nao-util" bit DEFAULT 1 NOT NULL,
	"rend-tribut" numeric(17,2) DEFAULT 0,
	"utiliza-verba" bit DEFAULT 0 NOT NULL,
	"percent-verba" numeric(17,2) DEFAULT 0 NOT NULL,
	endereco_text varchar(4000),
	"endereco-cob-text" varchar(4000),
	"short-name" varchar(32),
	"log-controla-val-max-inss" bit DEFAULT 0,
	"cod-inscr-inss" varchar(40),
	"cod-pulmao" varchar(10),
	"idi-tributac-cofins" integer DEFAULT 2 NOT NULL,
	"idi-tributac-pis" integer DEFAULT 2 NOT NULL,
	"log-calcula-pis-cofins-unid" bit DEFAULT 0 NOT NULL,
	"log-optan-suspens-ipi" bit DEFAULT 0 NOT NULL,
	"log-optan-cr-presmdo-subst" bit DEFAULT 0 NOT NULL,
	"retem-pagto" bit DEFAULT 0 NOT NULL,
	"portador-ap" integer DEFAULT 0 NOT NULL,
	"modalidade-ap" integer DEFAULT 1 NOT NULL,
	"log-contribt-subst-interm" bit DEFAULT 0 NOT NULL,
	"dat-valid-suframa" date DEFAULT NULL,
	"nom-fantasia" varchar(120),
	"log-possui-nf-eletro" bit DEFAULT 0 NOT NULL,
	"log-nf-eletro" bit DEFAULT 0,
	"dt-atualiza" date DEFAULT NULL,
	"hra-atualiz" varchar(16) DEFAULT '000000',
	"cod-email-nfe" varchar(1000),
	"log-integr-totvs-colab-vendas" bit DEFAULT 0,
	"cdn-atraso-max" integer DEFAULT 0,
	"dat-nasc" date DEFAULT NULL,
	"log-beneficiario" bit DEFAULT 0,
	"log-isenta-anexo" bit DEFAULT 0,
	CONSTRAINT codigo PRIMARY KEY ("cod-emitente")
);
CREATE INDEX cgc ON PUB.emitente (cgc);
CREATE INDEX "ch-cobranca" ON PUB.emitente ("end-cobranca","nome-abrev");
CREATE INDEX "ch-conpag" ON PUB.emitente ("cod-cond-pag");
CREATE INDEX "ch-matriz" ON PUB.emitente ("nome-matriz");
CREATE INDEX "ch-natope" ON PUB.emitente ("nat-operacao");
CREATE INDEX "ch-pais" ON PUB.emitente (pais);
CREATE INDEX "ch-portador" ON PUB.emitente (portador,modalidade);
CREATE INDEX "ch-prog-emit" ON PUB.emitente ("prog-emit","cod-emitente");
CREATE INDEX "ch-short-name" ON PUB.emitente ("short-name");
CREATE INDEX "emtclnfr-19" ON PUB.emitente (cidade,"cod-emitente");
CREATE INDEX "emtclnfr-20" ON PUB.emitente ("nome-tr-red");
CREATE INDEX "emtclnfr-21" ON PUB.emitente ("dt-atualiza","hra-atualiz");
CREATE INDEX "gr-mic-cli" ON PUB.emitente ("cod-gr-cli","nome-mic-reg","cod-emitente");
CREATE INDEX "grupo-cli" ON PUB.emitente ("cod-gr-cli","cod-emitente");
CREATE INDEX "grupo-fornec" ON PUB.emitente ("cod-gr-forn","cod-emitente");
CREATE INDEX "micro-reg" ON PUB.emitente ("nome-mic-reg","cod-emitente");
CREATE UNIQUE INDEX nome ON PUB.emitente ("nome-abrev");
CREATE INDEX repres ON PUB.emitente ("cod-rep","cod-emitente");
CREATE INDEX transporte ON PUB.emitente ("cod-transp","cod-emitente");


-- PUB.repres definição

-- Drop table

-- DROP TABLE PUB.repres;

CREATE TABLE PUB.repres (
	"cod-rep" integer DEFAULT 0 NOT NULL,
	nome varchar(80) NOT NULL,
	"nome-abrev" varchar(24) NOT NULL,
	natureza integer DEFAULT 1 NOT NULL,
	"nome-ab-reg" varchar(24) NOT NULL,
	endereco varchar(80) NOT NULL,
	bairro varchar(60) NOT NULL,
	cep varchar(24) NOT NULL,
	cidade varchar(50) NOT NULL,
	estado varchar(8) NOT NULL,
	pais varchar(40) NOT NULL,
	"caixa-postal" varchar(20) NOT NULL,
	cgc varchar(36),
	telefone varchar(64) NOT NULL,
	"inscr-est" varchar(38) NOT NULL,
	"rep-indireto" integer DEFAULT 0 NOT NULL,
	"comis-direta" numeric(17,2) DEFAULT 0 NOT NULL,
	"comis-emis" numeric(17,2) DEFAULT 0,
	"comis-indir" numeric(17,2) DEFAULT 0 NOT NULL,
	telex varchar(30) NOT NULL,
	telefax varchar(30) NOT NULL,
	"telef-modem" varchar(30),
	"perc-aire" numeric(17,2) DEFAULT 0 NOT NULL,
	"comis-max" numeric(17,2) DEFAULT 0 NOT NULL,
	"comis-min" numeric(17,2) DEFAULT 0 NOT NULL,
	"ins-municipal" varchar(38) NOT NULL,
	"zip-code" varchar(24),
	permissao varchar(144) DEFAULT '*' NOT NULL,
	"e-mail" varchar(160),
	"home-page" varchar(80),
	Complemento varchar(80),
	"char-1" varchar(200),
	"char-2" varchar(200),
	"dec-1" numeric(23,8) DEFAULT 0,
	"dec-2" numeric(23,8) DEFAULT 0,
	"int-1" integer DEFAULT 0,
	"int-2" integer DEFAULT 0,
	"log-1" bit DEFAULT 0,
	"log-2" bit DEFAULT 0,
	"data-1" date DEFAULT NULL,
	"data-2" date DEFAULT NULL,
	"check-sum" varchar(40),
	"cod-portador-geracao-ad" integer DEFAULT 0 NOT NULL,
	"dt-deslig" date DEFAULT NULL,
	"fc-codigo" integer DEFAULT 0,
	"perc-abatimento" numeric(17,2) DEFAULT 0,
	"perc-juros" numeric(17,2) DEFAULT 0,
	"perc-multa" numeric(17,2) DEFAULT 0,
	"perc-desconto" numeric(17,2) DEFAULT 0,
	"perc-AVA" numeric(17,2) DEFAULT 0,
	"cod-emitente" integer DEFAULT 0,
	"bloqueado-pagto" bit DEFAULT 0,
	"cod-tax" integer DEFAULT 0,
	"tipo-repres" integer DEFAULT 1,
	"comis-propor" bit DEFAULT 1,
	"tipo-comis" integer DEFAULT 1,
	"calendario-pagto" varchar(6),
	"vl-minimo-comis" numeric(17,2) DEFAULT 0,
	"mo-codigo" integer DEFAULT 0,
	"cod-retencao" integer DEFAULT 0,
	"cod-tax-indeniz" integer DEFAULT 0,
	"cod-retenc-indeniz" integer DEFAULT 0,
	"ind-situacao" integer DEFAULT 1,
	endereco_text varchar(4000),
	"log-consid-repres-cotas" bit DEFAULT 1,
	"cod-formula" varchar(24) NOT NULL,
	"idi-tip-comis-agent" integer DEFAULT 1 NOT NULL,
	"idi-tip-base-comis-agent" integer DEFAULT 1 NOT NULL,
	"idi-liber-pagto-comis-agent" integer DEFAULT 1 NOT NULL,
	"log-interm" bit DEFAULT 0,
	"nom-usuar-interm" varchar(120),
	CONSTRAINT codigo PRIMARY KEY ("cod-rep")
);
CREATE UNIQUE INDEX abrev ON PUB.repres ("nome-abrev");
CREATE INDEX "ch-regiao" ON PUB.repres ("nome-ab-reg");
CREATE INDEX indireto ON PUB.repres ("rep-indireto");
CREATE INDEX nome ON PUB.repres (nome);