-- PUB.campanha_caixa definição

-- Drop table

-- DROP TABLE PUB.campanha_caixa;

CREATE TABLE PUB.campanha_caixa (
	"it-codigo" varchar(32),
	"cod-canal-venda" integer DEFAULT 0,
	"nome-ab-reg" varchar(24),
	data_inicio date DEFAULT NULL,
	data_fim date DEFAULT NULL,
	valor_gera_verba numeric(17,2) DEFAULT 0,
	preco_gera_verba numeric(17,2) DEFAULT 0,
	char_1 varchar(16),
	int_1 integer DEFAULT 0,
	dec_1 numeric(17,2) DEFAULT 0,
	data_1 timestamp DEFAULT NULL,
	log_1 bit DEFAULT 0
);
CREATE INDEX i1 ON PUB.campanha_caixa ("it-codigo","cod-canal-venda","nome-ab-reg",data_inicio,data_fim);


-- PUB.campanha_com definição

-- Drop table

-- DROP TABLE PUB.campanha_com;

CREATE TABLE PUB.campanha_com (
	cod_campanha integer DEFAULT 0,
	descr_campanha varchar(60),
	data_inicio date DEFAULT NULL,
	data_fim date DEFAULT NULL,
	dec_1 numeric(17,2) DEFAULT 0,
	dec_2 numeric(17,2) DEFAULT 0,
	int_1 integer DEFAULT 0,
	int_2 integer DEFAULT 0,
	char_1 varchar(100),
	char_2 varchar(100),
	log_1 bit DEFAULT 1,
	log_2 bit DEFAULT 1,
	CONSTRAINT i1 PRIMARY KEY (cod_campanha)
);
CREATE INDEX i2 ON PUB.campanha_com (descr_campanha);


-- PUB.cliente_inf_adic definição

-- Drop table

-- DROP TABLE PUB.cliente_inf_adic;

CREATE TABLE PUB.cliente_inf_adic (
	cnpj varchar(38),
	nome_contato varchar(80),
	cargo_contato varchar(60),
	fone_contato varchar(60),
	fone_fax varchar(60),
	email_finance varchar(200),
	agendar_entrega bit DEFAULT 1,
	desmemb_pedido bit DEFAULT 1,
	horario_entrega varchar(200),
	char_1 varchar(16),
	log_1 bit DEFAULT 0,
	int_1 integer DEFAULT 0,
	organizacao varchar(30),
	central_compras varchar(30),
	"cod-emitente" integer DEFAULT 0,
	cod_banco varchar(16),
	cod_agenc_bcia varchar(20),
	cod_digito_agenc_bcia varchar(4),
	cod_cta_corren_bco varchar(40),
	cod_digito_cta_corren varchar(4),
	cnpj_conta varchar(40),
	entrega_agendar varchar(2),
	pedido_desmemb varchar(2),
	lim_disponivel numeric(17,2) DEFAULT 0,
	lim_credito numeric(17,2) DEFAULT 0,
	data_lim_credito date DEFAULT NULL,
	user_lib_credito varchar(30),
	nova_matriz varchar(30),
	dt_impl_web date DEFAULT NULL,
	dt_aprova_cr date DEFAULT NULL,
	dt_efetiva_coml date DEFAULT NULL,
	status_cadastro integer DEFAULT 0,
	cod_canal_venda integer DEFAULT 0,
	atividade varchar(24),
	nat_oper_int varchar(12),
	nat_oper_ext varchar(12),
	nro_lojas integer DEFAULT 0,
	lim_sugerido numeric(17,2) DEFAULT 0,
	cod_canal_preco integer DEFAULT 0,
	"cod-estabel" varchar(6),
	cod_tabela varchar(30),
	fg_atu_cli varchar(2),
	"l-merc-pallet" bit DEFAULT 0,
	"i-forma-pallet" integer DEFAULT 0,
	"l-custo-descarga" bit DEFAULT 0,
	"d-valor-custo-carga" numeric(17,2) DEFAULT 0,
	"i-tipo-custo" integer DEFAULT 0,
	"hr-ini-nf" varchar(16),
	"hr-fim-nf" varchar(16),
	"hr-ini-veiculo" varchar(16),
	"hr-fim-veiculo" varchar(16),
	"hr-ini-rec" varchar(16),
	"hr-fin-rec" varchar(16),
	"dt-atual-logistica" date DEFAULT NULL,
	"cod-usuario-log" varchar(24),
	"i-agendamento" integer DEFAULT 0,
	"cod-usuario-fin" varchar(24),
	"dt-atual-financeiro" date DEFAULT NULL,
	"dt-atual-venda" date DEFAULT NULL,
	"cod-usuario-venda" varchar(24),
	fg_perm_vend_atu_cli varchar(2),
	TipodeCadastro varchar(2),
	latualiza_cliente bit DEFAULT 0,
	lpermite_venda_atualiza bit DEFAULT 1,
	"d-valor-custo-carga2" numeric(17,2) DEFAULT 0,
	"l-atende" bit DEFAULT 1,
	qtdcxfugini integer DEFAULT 0,
	qtdcxcliente integer DEFAULT 0,
	inf_adicionais varchar(1000),
	"frequencia-visita" integer DEFAULT 0,
	"nr-check-out" integer DEFAULT 0,
	canal_distrib varchar(40),
	credito numeric(17,2) DEFAULT 0,
	data_fundacao date DEFAULT NULL,
	fornecedor_1 varchar(200),
	fornecedor_2 varchar(200),
	fornecedor_3 varchar(200),
	"imovel-proprio" varchar(2),
	atend_televendas bit DEFAULT 1,
	compra_fugini bit DEFAULT 1,
	cod_canal_comercial varchar(20),
	qtd_vendedores integer DEFAULT 0,
	qtd_lojas_cliente integer DEFAULT 0,
	sede varchar(200),
	capacid_armaz numeric(17,2) DEFAULT 0,
	outro_formato_atend varchar(200),
	venda_por_vendedores bit DEFAULT 0,
	tem_televendas bit DEFAULT 0,
	formato_venda_balcao bit DEFAULT 0,
	atualz_cad_cli varchar(2) DEFAULT '0',
	recolher_guia bit DEFAULT NULL,
	clie_ramy bit DEFAULT 0,
	regime_trib varchar(16),
	opt_cred_outorg bit DEFAULT 0,
	cnpj_blun varchar(40),
	clie_fugini bit DEFAULT 0,
	merchan_erc integer DEFAULT 0,
	clie_camp_food varchar(16),
	clie_recup_jud varchar(16),
	foco_atendim varchar(90),
	varied_produtos varchar(90),
	equipe_vendas varchar(10),
	tam_equipe integer DEFAULT 0,
	qtde_produtos integer DEFAULT 0,
	flag_serv_aliment varchar(10),
	nro_funciona integer DEFAULT 0,
	faturam_estim varchar(90),
	tipo_chave_pix varchar(90),
	chave_pix varchar(90),
	regim_empresa varchar(90),
	possui_regim_espec varchar(6),
	descr_regim_espec varchar(90),
	possui_cd varchar(6),
	paletiz_pad_fugini varchar(6),
	altura_pallet integer DEFAULT 0,
	qtde_cxs_pallet integer DEFAULT 0,
	retric_area varchar(6),
	restric_veiculo varchar(6),
	restric_tp_veic varchar(90),
	altura_veic_restrit integer DEFAULT 0,
	restric_bau_veic varchar(6),
	descr_restric_bau varchar(200),
	carga_exclusiva varchar(6),
	classif_estabel varchar(90),
	tp_bairro varchar(90),
	comprim_estabel numeric(18,3) DEFAULT 0,
	largura_estabel numeric(18,3) DEFAULT 0,
	area_estabel numeric(18,3) DEFAULT 0,
	CONSTRAINT i1 PRIMARY KEY (cnpj)
);
CREATE INDEX i2 ON PUB.cliente_inf_adic ("cod-emitente");


-- PUB.item_pre_pedido definição

-- Drop table

-- DROP TABLE PUB.item_pre_pedido;

CREATE TABLE PUB.item_pre_pedido (
	"nome-abrev" varchar(24),
	"nr-pedcli" varchar(24),
	"it-codigo" varchar(32),
	preco_unit numeric(17,2) DEFAULT 0,
	qtde_pedida numeric(17,2) DEFAULT 0,
	perc_desconto numeric(17,2) DEFAULT 0,
	qtde_bonificada numeric(17,2) DEFAULT 0,
	perc_comissao numeric(17,2) DEFAULT 0,
	vlr_tot_item numeric(17,2) DEFAULT 0,
	preco_orig numeric(20,5) DEFAULT 0,
	vlr_verba_item numeric(17,2) DEFAULT 0,
	vlr_comissao numeric(17,2) DEFAULT 0,
	vlr_bonificacao numeric(17,2) DEFAULT 0,
	bonif_promocional numeric(17,2) DEFAULT 0,
	preco_inform numeric(20,5) DEFAULT 0,
	"ep-codigo" integer DEFAULT 1,
	char_2 varchar(16),
	dec_1 numeric(17,2) DEFAULT 0,
	dec_2 numeric(17,2) DEFAULT 0,
	int_1 integer DEFAULT 0,
	int_2 integer DEFAULT 0,
	char_1 varchar(16),
	log_2 bit DEFAULT 0,
	log_1 bit DEFAULT 0,
	vlr_bruto_item numeric(17,2) DEFAULT 0,
	"cod-estabel" varchar(10),
	vlr_verba_afv numeric(17,2) DEFAULT 0,
	obs_item varchar(200),
	cod_tabela varchar(30),
	vlr_st_item numeric(17,2) DEFAULT 0,
	dec_3 varchar(160) DEFAULT '0',
	CONSTRAINT i1 PRIMARY KEY ("nome-abrev","nr-pedcli","it-codigo","ep-codigo")
);


-- PUB.pre_pedido definição

-- Drop table

-- DROP TABLE PUB.pre_pedido;

CREATE TABLE PUB.pre_pedido (
	"nome-abrev" varchar(24),
	"nr-pedcli" varchar(24),
	"nr-pedido" integer DEFAULT 0,
	"cod-estabel" varchar(6),
	"vl-tot-ped" numeric(17,2) DEFAULT 0,
	"vl-desconto" numeric(17,2) DEFAULT 0,
	"vl-liq-ped" numeric(17,2) DEFAULT 0,
	desc_status varchar(80),
	"dt-implant" date DEFAULT NULL,
	"cod-emitente" integer DEFAULT 0,
	"cod-cond-pag" integer DEFAULT 0,
	"dt-entrega" date DEFAULT sysdate,
	"cod-entrega" varchar(24),
	observacao varchar(4000),
	"no-ab-reppri" varchar(24),
	"cidade-cif" varchar(50),
	"nr-tabpre" varchar(16),
	"log-cotacao" bit DEFAULT 1,
	perc_comissao numeric(17,2) DEFAULT 0,
	id_status integer DEFAULT 1,
	desc_justificativa varchar(4000),
	desc_aprovacao varchar(4000),
	vlr_verba_pedido numeric(17,2) DEFAULT 0,
	vlr_tot_comissao numeric(17,2) DEFAULT 0,
	vlr_tot_bonific numeric(17,2) DEFAULT 0,
	tp_transporte integer DEFAULT 1,
	tp_bonificacao integer DEFAULT 1,
	desc_comercial numeric(17,2) DEFAULT 0,
	desc_promocional numeric(17,2) DEFAULT 0,
	lg_tabloide bit DEFAULT 0,
	"hr-implant" varchar(16) DEFAULT '1000',
	desc_risk varchar(80),
	semaforo integer DEFAULT 0,
	"cond-redespa" varchar(4000),
	"cond-espec" varchar(4000),
	desc_comercial_ext varchar(64) DEFAULT '0',
	desc_promocional_ext varchar(64) DEFAULT '0',
	int_2 integer DEFAULT 0,
	char_1 varchar(100),
	char_2 varchar(100),
	dec_1 numeric(17,2) DEFAULT 0,
	dec_2 numeric(17,2) DEFAULT 0,
	int_1 integer DEFAULT 0,
	acordo varchar(192) DEFAULT '0',
	campanha varchar(192) DEFAULT '0',
	log_1 bit DEFAULT 0,
	log_2 bit DEFAULT 0,
	desc_comercial_ger varchar(192) DEFAULT '0',
	"cod-rep" integer DEFAULT 0,
	"nr-pedafv" varchar(60),
	"usuar-aprov" varchar(30),
	"cod-sit-ped" integer DEFAULT 0,
	"cod-sit-aval" integer DEFAULT 0,
	"data-aprov" date DEFAULT NULL,
	int_3 integer DEFAULT 0,
	i_aprovado integer DEFAULT 0,
	aprovador varchar(24),
	hr_aprovacao varchar(16),
	lg_cantinho varchar(240) DEFAULT '0',
	int_4 integer DEFAULT 0,
	dt_import timestamp DEFAULT NULL,
	dt_ent_orig date DEFAULT NULL,
	dt_reprova date DEFAULT NULL,
	cod_preposto varchar(20),
	data_fatur date DEFAULT NULL,
	ped_sugest varchar(2),
	ped_vinculado varchar(2),
	"tp-pedido" varchar(4),
	ord_compra_clie varchar(60),
	vl_tot_st numeric(17,2) DEFAULT 0,
	aplicar_desconto integer DEFAULT 0,
	status_pedido integer DEFAULT 0,
	status_mail_trans integer DEFAULT 0,
	"perc-desco1" numeric(17,2) DEFAULT 0,
	metodo_pagto varchar(200),
	CONSTRAINT i2 PRIMARY KEY ("nome-abrev","nr-pedcli")
);
CREATE INDEX i1 ON PUB.pre_pedido ("nr-pedcli");
CREATE INDEX i3 ON PUB.pre_pedido (id_status);
CREATE INDEX i4 ON PUB.pre_pedido ("dt-implant","no-ab-reppri",id_status);
CREATE INDEX i5 ON PUB.pre_pedido ("nr-pedafv");